invenio_communities/templates/communities/index_base.html, invenio_communities/templates/communities/mycommunities_base.html
* Places heading before search field. This is more logical and improves
flow. Downgrades heading to level 2, because it is not the page title
(which is Invenio) and it makes longer text better readable on
smaller screens.
* Readjusts construction of title + button of listed communities, so
long titles do not flow into the buttons. Removes hardcoded style
values as well.
* Aligns 'My Communities'>{'New','Sign Up'] button with the heading.
* Extracts static `communitiy.css` from template.
Signed-off-by: Marco Neumann <marco@crepererum.net>
Rebased against: `master`
Extracted from inveniosoftware/invenio#3069
=> communities: page reorder

invenio_communities/upgrades/communities_2014_03_07_ranker.py, invenio_communities/upgrades/communities_2014_10_17_featured_communities.py, requirements-devel.txt, setup.py
* FIX Fixes import of invenio_upgrader in the past upgrade recipes
following its separation into standalone package.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> global: fix import of invenio_upgrader

AUTHORS.rst, invenio_communities/models.py, requirements-devel.txt, setup.py
* Adds missing `invenio_access` dependency and amends past upgrade
recipes following its separation into standalone package.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> installation: fix invenio_access import

invenio_communities/bundles.py, invenio_communities/forms.py, invenio_communities/models.py, invenio_communities/tasks.py, invenio_communities/views.py, requirements-devel.txt, setup.py, tests/test_communities.py, tests/test_featured_community.py
* FIX Adds missing `invenio_base` dependency and amends past
upgrade recipes following its separation into standalone package.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> installation: fix invenio_base imports

.travis.yml, pytest.ini, requirements-devel.txt, setup.py, tests/test_communities.py, tests/test_featured_community.py, tests/test_views.py
* FIX Removes calls to PluginManager
consider_setuptools_entrypoints() removed in PyTest 2.8.0.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> tests: fix incompatibility with pytest>=2.8.0

invenio_communities/models.py, invenio_communities/views/api.py, tests/test_invenio_communities.py
* Adds the etag header to the details of each community. (closes #38)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
=> rest: addition of etag to community details

invenio_communities/models.py, setup.py, tests/conftest.py, tests/test_invenio_communities.py
* Fixes the issue with accepting and removing communities raising assertion
errors on external modification of 'communities' key in record.
=> global: communities accept/remove bugfix

.editorconfig, invenio_communities/alembic/2d9884d0e3fa_create_community_tables.py, invenio_communities/models.py, invenio_communities/utils.py, requirements-devel.txt
* Fixes an email rendering bug, caused by a context variable being
a tuple because of a trailing comma. (closes #92)
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
=> email: template context variable fix

invenio_communities/templates/invenio_communities/new.html
The field description in the new.html did not allow links, as the type was 'simple'. With type 'advanced' links are allowed.
=> templates: description changed simple to advanced

invenio_communities/templates/invenio_communities/mycommunities.html
Flask-Security allows to deactivate user registration, which is useful if only SSO should be allowed using the configuration variable (`SECURITY_REGISTERABLE`, https://pythonhosted.org/Flask-Security/configuration.html?highlight=security_registerable#feature-flags)
If the user is currently not authenticated and `SECURITY_REGISTERABLE = False` the invenio-communities frontpage shows an internal server error. (The endpoint cannot be built.)
Changed myccommunities template to show login button instead of Sign Up in case  `SECURITY_REGISTERABLE = False`.
If you prefer another solution, just tell me, but would be important for me to have a solution.
Fixes #105
=> Fix Internal Server Error if SECURITY_REGISTERABLE is False

invenio_communities/models.py
Fixes tests with sqlite that break due to missing constraint name for a Boolean constraint.
(fixes this error: 
`sqlalchemy.exc.InvalidRequestError: Naming convention including %(constraint_name)s token requires that constraint is explicitly named.`)
=> models: name Boolean constraint

CHANGES.rst, invenio_communities/ext.py, invenio_communities/marshmallow/json.py, invenio_communities/version.py, run-tests.sh
Loading errors do not occur anymore. However, I have not tested communities functionality after the changes.
=> config: set default records rest to avoid order errors

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/RenameCommunityButton.js
=> communities-profile: fix validation message on rename

invenio_communities/ext.py
- closes #349 
The first screenshot shows the API `url_map` with `COMMUNITIES_ENABLED=False`, the second with `COMMUNITIES_ENABLED=True`.
=> ext: do not register routes and service if disabled

invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json, invenio_communities/communities/records/jsonschemas/communities/definitions-v2.0.0.json, invenio_communities/communities/records/systemfields/access.py, invenio_communities/communities/records/systemfields/owners.py, invenio_communities/communities/schema.py, invenio_communities/communities/services/components.py, invenio_communities/communities/services/permissions.py, setup.py, tests/communities/alembic/test_alembic.py, tests/conftest.py
Depends on PR in Invenio-Vocabularies yet to be opened.
This PR removes the dependency on Invenio-RDM-Records. This is a first step which duplicates part of the code. A further step is needed later to move the duplicated code to Invenio-Records-Resources/Permissions and make both RDM-Records and Communities use this. Some design changes are however needed, to make it more reusable, and thus this is only a first step to untangle deps.
=> global: remove invenio-rdm-records as dependency

invenio_communities/communities/__init__.py, invenio_communities/communities/services/__init__.py, invenio_communities/communities/services/permissions.py, invenio_communities/ext.py, invenio_communities/requests/resolver.py, invenio_communities/utils.py
Add Community Needs (currently only hinting at ownership of a community, because we don't have any other memberships yet), and add a function which automatically adds the Community Needs to a user's identity for all communities owned by said user.
Because this function is called very often (every request), we cache the results in the session and use a timeout-based mechanism for invalidating the cache.
This will have to be revisited when we have community memberships.
=> Community Needs

invenio_communities/assets/semantic-ui/less/invenio_communities/theme.less, invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
closes: inveniosoftware/invenio-communities#400
Without hidden divider.
With hidden divider.
=> Communities: remove bottom padding from community header

invenio_communities/permissions.py
To be honest, the system process can probably just do everything.
In which case, it might be best to add it to invenio-rdm-permissions
like we did for the admin user, so that we don't have to add it
everywhere in the future.
This came about while working on our importer.
=> allow system process to read communities

invenio_communities/members/services/service.py, tests/members/test_members_services.py
* The list of invitations should also display accepted invitations.
**Reminder**
2. You agree that you have the right to license your …
=> members: list also accepted invitations

invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html
Closes [#1431](https://github.com/inveniosoftware/invenio-app-rdm/issues/1431)
Need https://github.com/inveniosoftware/invenio-app-rdm/pull/1445 to make the container (w/background color) span the full width of the page. 
*Note:* Please ignore the global header menu which is overlapping on mobile&tablet (solved in a different PR).
=> frontpage: align community header content

invenio_communities/members/services/service.py, tests/members/test_members_resource.py
closes #495 
Pass along `params` and `es_preferences` to other functions in the search methods for members and invitations. 
**Reminder**
1. You license your contribution under the same terms as …
=> fix: pass along params and es_preferences

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SearchResultsBulkActions.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SelectedMembers.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMemberBulkActions.js
- the dropdown action can now be selected again
- now does not trigger the action on blur
- disabled the dropdown menu items if nothing is selected 
- added aria labels for ay11
closes https://github.com/inveniosoftware/invenio-communities/issues/529
=> members list: fix bulk action dropdown

invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json, invenio_communities/communities/resolver.py, invenio_communities/communities/services/service.py, setup.cfg
* adds the UUID field to the ES mapping as keyword
* enhances the community resolver to inject the service and pick the
fields to be expanded when resolved
* removes dependency invenio-users-resources, added to invenio-requests
* overrides the default service read_many to search by uuid
requires https://github.com/inveniosoftware/invenio-requests/pull/202
=> global: enhance resolver and add uuid to ES mappings

invenio_communities/communities/services/components.py, invenio_communities/members/services/request.py, invenio_communities/views/communities.py
- closes https://github.com/inveniosoftware/invenio-communities/issues/607
Since all the occurrences happen at _views_ level it is accepted to access the `g` object. The `current_user` does not provide an identity (it provides `id` and `roles`) and we would need to build the identity from it, which is already stored in `g.identity`.
=> permissions: remove usage of system_identity on service calls

invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MemberSearchBar.js
Now clear the search bar error state when a following request is successful
closes https://github.com/inveniosoftware/invenio-communities/issues/612
=> invitations: clear search error state on success

invenio_communities/members/services/service.py
- closes https://github.com/inveniosoftware/invenio-communities/issues/622
The following is a screenshot of how it looks now. Having a custom field name `members` does not seem ideal. However, any other type of fix requires a lot of custom logic and changes to the `ErrorMessage` component that might have wider effects.
Note: there are many other occurences of `ValidationError`s without a `field_name` accross the code base. Shall we open an issue to investigate and fix them? Having a `field_name` is a good practice (since is a Marshmallow exception) because otherwise it defaults to root `_schema`.
=> communities: add field name to service ValidationError

invenio_communities/members/services/service.py, tests/members/test_members_resource.py, tests/members/test_members_services.py
- closes #557 
How it looks:
Wokflow:
1. Note the capitalization issue
2. Is there a better phrasing than "You would join as..."
https://user-images.githubusercontent.com/6756943/167810741-4839730e-94d7-4aaf-90e5-9ecaac039799.mov
=> members: move role information to separate message

invenio_communities/assets/semantic-ui/js/invenio_communities/community/frontpage.js
**Needs PR** https://github.com/inveniosoftware/invenio-app-rdm/pull/1542
Makes community images same size in the front page cards container.
=> community card: make images same size

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ActionDropdown.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultContainer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js
made the visibility dropdown update the permissions so that it can properly display if the visibility can be changed. Also fixed the alignment on the response icons triggered by using the action dropdown
closes https://github.com/inveniosoftware/invenio-communities/issues/603
needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1538
=> members: fix visibility dropdown and response icons

invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js, invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1547
**Related PR** https://github.com/inveniosoftware/invenio-app-rdm/pull/1563
Changed the arrow icon to <Button/> to ensure that the icon is accessible by keyboard and with a screen reader.
Tested with VoiceOver on Mac.
=> parent facet value: change arrow icon to button for a11y

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
**Needs** https://github.com/inveniosoftware/invenio-app-rdm/pull/1574
Reduced the amount of space needed for the header content.
- Moved description to accordion
- Changed details listing to be inline on computer (needs PR mentioned above - use of `.flex` does not solve the issue, as this class does not break the content on smaller screens.)
- Made logo slightly smaller on tablet
=> community header: layout improvements

invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js, invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js
search bar now correctly triggers a search event in the communities search page and now correctly holds the filter state and query string while switching between modes
in the communities requests page
closes https://github.com/inveniosoftware/invenio-communities/issues/695
closes https://github.com/inveniosoftware/invenio-communities/issues/697
=> communities: fix searchbar behaviour

invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultContainer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js
Closes closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1735
Context:
- On mobile, the table headers are removed (using css) and data-labels are aligned with the table data. 
- Styling rules were being applied specifically for this table but could be re-used, provided a class name that is more function oriented and less context oriented.
=> community: updated members table

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ActionDropdown.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1714
The issue was that the dropdown container width was adjusting when the icon rendered. E.g. when the icon was rendered, the dropdown container shrinked.
This fix reserves space for the success/error icon by creating a `div`. Does not reduce the dropdown size a lot and it's enough to make the whole cell static when changing the selection.
=> members: reserves space for success/error icon

invenio_communities/members/services/components.py, invenio_communities/members/services/config.py, invenio_communities/members/services/service.py, invenio_communities/utils.py, tests/communities/test_services.py, tests/members/test_members_components.py, tests/members/test_members_services.py
closes #508 
depends on #773 (for group caching test case)
Runs the components for methods which modify users.
Reactivates permission caching for communities. A cached entry is removed on `accept_invite`, `add`, `update`, `delete`.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contrib …
=> 508 backend communities permission cachingidentity loading

invenio_communities/members/services/config.py, invenio_communities/members/services/service.py, invenio_communities/views/api.py, tests/conftest.py, tests/members/conftest.py
Make the `service.rebuild_index` method use bulk indexing rather than indexing each item individually.
Related to https://github.com/inveniosoftware/invenio-records-resources/pull/419.
=> Bulk indexing for members/invitations `rebuild_index`

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities-carousel/CommunitiesCarousel.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities-carousel/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities-carousel/override.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js, invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js, invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SearchResultsBulkActions.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SearchResultsBulkActionsManager.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchLayout.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/components/MembersSearchLayout.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/member_view/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/public_view/PublicMembersSearchLayout.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/public_view/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/requests/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js, invenio_communities/templates/semantic-ui/invenio_communities/details/members/invitations.html, invenio_communities/templates/semantic-ui/invenio_communities/details/members/members.html, invenio_communities/templates/semantic-ui/invenio_communities/details/requests/index.html, invenio_communities/templates/semantic-ui/invenio_communities/search.html
* namespaces search apps
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2018
=> overridable: enable components to be overriden

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/curation-policy/CurationPolicyForm.js, invenio_communities/assets/semantic-ui/js/invenio_communities/settings/curation-policy/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js, invenio_communities/config.py, invenio_communities/templates/semantic-ui/invenio_communities/details/about/index.html, invenio_communities/templates/semantic-ui/invenio_communities/details/curation_policy/index.html, invenio_communities/templates/semantic-ui/invenio_communities/details/header.html, invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html, invenio_communities/templates/semantic-ui/invenio_communities/details/settings/curation_policy.html, invenio_communities/templates/semantic-ui/invenio_communities/details/upload-instructions.html, invenio_communities/views/communities.py, invenio_communities/views/ui.py, invenio_communities/webpack.py, tests/conftest.py
Closes https://github.com/inveniosoftware/invenio-communities/issues/867
Needs https://github.com/inveniosoftware/invenio-app-rdm/pull/2057
- Moved the about section from the header to new tab
- Added  new tab for curation policy
- Added new tab on the settings page for curation policy
- Added TODO comment for updating the upload-instructions text
-  I renamed the "Description" field in the settings page to "Summary", as we have the "Page description" below. This will show up above the "page description" on the about page (see above divider in the about page - next screenshot). Let me know if this should be renamed, or solved differently?
=> community details: add about and curation policy tab

CHANGES.rst, invenio_communities/__init__.py, invenio_communities/communities/schema.py, invenio_communities/communities/services/components.py, invenio_communities/communities/services/config.py, invenio_communities/communities/services/facets.py, invenio_communities/config.py, invenio_communities/errors.py, invenio_communities/members/services/config.py, invenio_communities/members/services/facets.py, invenio_communities/members/services/fields.py, invenio_communities/members/services/request.py, invenio_communities/members/services/schemas.py, invenio_communities/members/services/service.py, invenio_communities/views/communities.py, invenio_communities/views/ui.py, setup.cfg
- migrate: flask_babelex replaced by invenio_i18n
- fix: black issues due to higher version
- NOTE invenio-i18n has to be released first
=> migrate to flask babel

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItem.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemMobile.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemMobile.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/labels/CommunityTypeLabel.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2182
**Needs** https://github.com/inveniosoftware/react-invenio-forms/pull/199
- Accessibility fixes
- Adds popup for review information (optional through `showPermissionLabel`-prop)
=> community items: accessibility & responsiveness improvements

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemMobile.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemMobile.js
Closes https://github.com/inveniosoftware/invenio-communities/issues/950
This PR makes the spacing in the CommunityItem more consistent by adding margins and preventing empty elements (with margins) to show up.
=> CommunityItem: Improve consistency of spacing

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/DeleteCommunityModal.js, invenio_communities/communities/services/config.py
* closes https://github.com/inveniosoftware/invenio-communities/issues/935
When a user decides to delete a community the Community Deletion Modal pops up, to make sure the user is aware of the impact of their actions. Some community metrics (member and record counts) are now displayed on the Community Deletion Modal. 
=> delete community: display metrics on deletion modal

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
Closes https://github.com/zenodo/zenodo-rdm/issues/409
Layout improvement for the community header.
See https://github.com/zenodo/zenodo-rdm/pull/411 for screenshots.
=> header: fix mobile version

invenio_communities/templates/semantic-ui/invenio_notifications/community-invitation.submit.jinja, tests/members/test_members_services.py
tests: adapt invitation notification testcase
Access invitation message via notification context in jinja template.
Adapt test to test for the (non-)existence of the message.
**Reminder**
1. You …
=> templates: access message and mark subject for translation

invenio_communities/templates/semantic-ui/invenio_communities/search.html
closes https://github.com/inveniosoftware/invenio-github/issues/115
- Changes header to h1 and aligns size with similar header for My account
=> search header: align style with My account header

invenio_communities/requests/user_moderation/__init__.py, invenio_communities/requests/user_moderation/actions.py, setup.cfg
closes https://github.com/inveniosoftware/invenio-users-resources/issues/95
=> requests: added moderation actions.

invenio_communities/templates/semantic-ui/invenio_communities/details/curation_policy/index.html, invenio_communities/templates/semantic-ui/invenio_communities/details/header.html, invenio_communities/views/decorators.py, invenio_communities/views/ui.py
Closes https://github.com/zenodo/rdm-project/issues/172, closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2327
- Removes "about" and/or "curation policy" tabs if no content
- Removes hard coded headline for Curation policy
No page contents added:
Only curation policy content added:
Both added:
=> details header: remove hardcoded header, remove empty tabs

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemMobile.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemMobile.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/frontpage.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/searchComponents/ResultsGridItemTemplate.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/components/MembersResultsGridItem.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/public_view/PublicMembersResultItem.js, invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js, invenio_communities/communities/schema.py, invenio_communities/fixtures/demo.py
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2216.
* Removes all unsafe rendering of community description as HTML.
* Limits the max length of a community description to 250 chars.
=> ui: safely render community `description`

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js
=> communities-profile: fix custom funding form

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemMobile.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2420
I added the icon as suggested in the issue, rather than the other suggestion of making the link select the community. I think this is the most intuitive behavior, as we have a select button on the item - it is also useful to have a way to view the community before selecting.
=> CommunityCompactItem: add external icon and target blank

invenio_communities/communities/resources/config.py, invenio_communities/communities/resources/ui_schema.py, invenio_communities/communities/services/components.py, invenio_communities/communities/services/config.py, invenio_communities/communities/services/service.py, invenio_communities/errors.py, invenio_communities/generators.py, invenio_communities/members/resources/config.py, invenio_communities/permissions.py, tests/communities/test_services.py
What's not included yet:
* hooking the deletion operations to resources
* deleting communities of users when they're getting blocked
=> Implement service methods for community deletion

invenio_communities/communities/resources/config.py
closes https://github.com/zenodo/rdm-project/issues/258
=> resources: add etag headers

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItem.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemMobile.js
* closes https://github.com/zenodo/rdm-project/issues/171
=> communityItem: add detailUrl

invenio_communities/administration/communities.py, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/api.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/api/api.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/api/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/api/routes.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/RecordResourceActions.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/RemovalReasonsSelect.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/RestoreConfirmation.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/TombstoneForm.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/search.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/search/RecordSearchLayout.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/search/filters/DeletionStatusFilter.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/search/filters/index.js, invenio_communities/communities/records/systemfields/deletion_status.py, invenio_communities/communities/resources/args.py, invenio_communities/communities/resources/config.py, invenio_communities/communities/resources/resource.py, invenio_communities/communities/services/components.py, invenio_communities/communities/services/config.py, invenio_communities/communities/services/search_params.py, invenio_communities/communities/services/service.py, invenio_communities/generators.py, invenio_communities/members/resources/config.py, invenio_communities/permissions.py, invenio_communities/requests/user_moderation/actions.py, invenio_communities/templates/semantic-ui/invenio_communities/tombstone.html, invenio_communities/views/ui.py, run-js-linter.sh, tests/communities/test_resources.py, tests/communities/test_services.py
When a user gets blocked, delete all communities of which they are the only owner
=> User moderation: Delete a user's communities on block

invenio_communities/templates/semantic-ui/invenio_notifications/community-invitation.accept.jinja, invenio_communities/templates/semantic-ui/invenio_notifications/community-invitation.cancel.jinja, invenio_communities/templates/semantic-ui/invenio_notifications/community-invitation.decline.jinja, invenio_communities/templates/semantic-ui/invenio_notifications/community-invitation.expire.jinja, invenio_communities/templates/semantic-ui/invenio_notifications/community-invitation.submit.jinja, tests/members/test_members_services.py
Updated the templates for notification emails
e.g.
**Reminder**
2. You agree that you have the right to …
=> emails: update templates

invenio_communities/errors.py
* closes https://github.com/zenodo/rdm-project/issues/492
Asks for a `num`: https://github.com/python-babel/flask-babel/blob/master/flask_babel/__init__.py#L662
=> translations: fix ngettext parameter

invenio_communities/config.py, invenio_communities/views/ui.py, tests/communities/tests_views.py
This update introduces a configurable option to control the visibility of the 'New Community' menu button in InvenioRDM based on user permissions and application configuration. When the corresponding configuration (COMMUNITIES_CREATE_PERM_CHECK) is set to false, the 'New Community' button is always visible to users. If set to true, the system checks whether the user has the necessary permission to create a community before displaying the button. This feature enhances administrative control and personalizes the user interface according to user roles and permissions.
Note: This functionality was previously enabled but encountered issues in Zenodo, leading to its temporary disablement. 
Ticks in all boxes and 🟢 on all GitHub actions status checks are …
=> views: Conditional New Community btn visibility

CHANGES.rst, invenio_communities/assets/semantic-ui/js/invenio_communities/community/CommunitiesCardGroup.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/frontpage.js, invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html
By decoupling the CommunitiesCardGroup definition and its ReactDOM.render, other
code can reuse the component independently.
Also renames featured-communities to new-communities because that's what it is.
=> frontpage: split component definition and app rendering [+]

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/DeleteButton.js, invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/DeleteCommunityModal.js, invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/LogoUploader.js
- closes https://github.com/inveniosoftware/invenio-communities/issues/326
- closes https://github.com/inveniosoftware/invenio-communities/issues/741
[change_profile.webm](https://github.com/inveniosoftware/invenio-communities/assets/1932651/85eb383a-1a2e-453c-9f29-98c7021bab9c)
- also fixes serious WCAG violation: id of active elements must be unique
=> community logo: fix update/delete wiping form

invenio_communities/communities/records/api.py, invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json, invenio_communities/communities/records/systemfields/parent_community.py, tests/communities/conftest.py, tests/communities/test_parent_community.py
* closes https://github.com/zenodo/zenodo-rdm/issues/696
=> systemfields: add parent community

invenio_communities/communities/records/api.py, invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json, invenio_communities/communities/records/mappings/os-v1/communities/communities-v1.0.0.json, invenio_communities/communities/records/mappings/os-v2/communities/communities-v1.0.0.json, invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json, invenio_communities/communities/records/systemfields/children.py, invenio_communities/communities/records/systemfields/parent_community.py, invenio_communities/communities/schema.py, invenio_communities/communities/services/components.py, invenio_communities/permissions.py, tests/communities/test_components.py, tests/communities/test_services.py
* updates schema to laod parent.id only
* closes https://github.com/zenodo/zenodo-rdm/issues/700
=> parent_community: use OS instead of DB queries for search result

invenio_communities/communities/records/mappings/os-v1/communities/communities-v1.0.0.json, invenio_communities/communities/records/mappings/os-v2/communities/communities-v1.0.0.json, invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json
- The mapping is stored as a string/enum in ES/OS. Using the same type
makes sure the mapping comparison is correct when performing a
mapping update.
=> mappings: change "dynamic" values to string

invenio_communities/communities/records/systemfields/parent_community.py, invenio_communities/records/records/systemfields/communities/field.py, invenio_communities/utils.py
Closes https://github.com/inveniosoftware/invenio-communities/issues/1089
=> refactor: move filter_dict_keys to invenio_records

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js, invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CustomFieldSerializer.js
Closes Issue [#733](https://github.com/zenodo/zenodo-rdm/issues/733)
**Reminder**
2. You agree that you …
=> custom_fields: added custom vocab flag

invenio_communities/members/records/models.py, tests/members/test_members_services.py
* Fixes an edge-case where if no filtering parameters are passed all
community/role pairs are returned.
=> models: fix memberships querying

invenio_communities/communities/records/api.py, invenio_communities/communities/records/systemfields/is_verified.py, invenio_communities/records/records/systemfields/communities/field.py, tests/communities/test_relations_organizations.py
* Denormalize is_verified into the record. INCOMPATIBLE: Needs update in in invenio-rdm-records mappings.
* Use cached value from index for is_verified instead of recomputing.
Depends on https://github.com/inveniosoftware/invenio-records-resources/pull/573
closes https://github.com/zenodo/ops/issues/398
=> records: optimize performance of is_verified

invenio_communities/ext.py, invenio_communities/views/ui.py
We noticed that the community CSS theme was not mapped, and found out that the problem was related to the pull request #958.
It is likely that the pull request was authored before other changes were introduced, and that rebasing accidentally rolled back these recent changes (since the PR consists of moving code between different files).
The changes which got rolled back by mistake are:
* Mapping of the CSS theme
* Some `visible_when` conditions
* The `order` of the menu items, but this was then also modified in the pull request #1125.
If you've added [third-party code (copy/pasted or new …
=> fix: community theme and menus visibility

invenio_communities/assets/semantic-ui/js/invenio_communities/api/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SearchWithRoleSelection.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsEmptyResults.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsResultsContainer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchLayout.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/GroupTabPane.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/InvitationsMembersModal.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MemberSearchBar.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerEmptyResults.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMemberBulkActions.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultContainer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerSearchLayout.js, invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/index.js, invenio_communities/config.py, invenio_communities/generators.py, invenio_communities/permissions.py, invenio_communities/templates/semantic-ui/invenio_communities/details/members/invitations.html, invenio_communities/templates/semantic-ui/invenio_communities/details/members/members.html, tests/members/test_members_no_groups.py
* deprecate COMMUNITIES_GROUPS_ENABLED (moved to USERS_RESOURCES_GROUPS_ENABLED)
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2592
Results counter:
Groups tab:
Changes in the **community add members** tab:
=> invitations: rework for the groups invitations

CHANGES.rst, invenio_communities/__init__.py
- Fix changes.rst file 
- Release a new version
- Removed tag `v2.8.10` from upstream
=> release: v2.8.11

invenio_communities/communities/resources/ui_schema.py
=> ui: fixed tombstone dumping.

invenio_communities/members/records/mappings/os-v1/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json, invenio_communities/members/records/mappings/os-v1/communitymembers/members/member-v1.0.0.json, invenio_communities/members/records/mappings/os-v2/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json, invenio_communities/members/records/mappings/os-v2/communitymembers/members/member-v1.0.0.json, invenio_communities/members/records/mappings/v7/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json, invenio_communities/members/records/mappings/v7/communitymembers/members/member-v1.0.0.json
The user profiles and preferences offer a mechanism to add custom fields, but the community members & invitations cannot handle anything unexpected.
This PR fixes that by adding the same `dynamic{,_templates}` settings present in the [users mappings](https://github.com/inveniosoftware/invenio-users-resources/blob/master/invenio_users_resources/records/mappings/os-v2/users/user-v2.0.0.json).
=> Invitations & members: Add dynamic mappings for user profiles and preferences

invenio_communities/assets/semantic-ui/js/invenio_communities/subcommunity/new.js
Closes issue https://github.com/zenodo/zenodo-rdm/issues/890
**Frontend**
**Reminder** …
=> Subcommunity: made the form overridable

invenio_communities/assets/semantic-ui/js/invenio_communities/subcommunity/new.js
Needs to be rebased once https://github.com/zenodo/zenodo-rdm/issues/904 is merged
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/903
**Frontend**
**Reminder**
1. You license your contribution under the …
=> subcommunity: updated fieldpaths in the ui

invenio_communities/communities/services/service.py
* logo file hasn't been deleted. this prevented a new file upload,
because of an sqlalchemy.exc.IntegrityError:
(psycopg2.errors.UniqueViolation) error.
this fixes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2698
=> fix(logo): not fully deleted

invenio_communities/assets/semantic-ui/js/invenio_communities/api/CommunityLinksExtractor.js, invenio_communities/assets/semantic-ui/js/invenio_communities/api/RequestLinksExtractor.js, invenio_communities/assets/semantic-ui/js/invenio_communities/api/membershipRequests/api.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/header/RequestMembershipButton.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/header/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges/CommunityPrivilegesForm.js, invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges/index.js, invenio_communities/communities/services/config.py, invenio_communities/config.py, invenio_communities/generators.py, invenio_communities/members/resources/config.py, invenio_communities/members/resources/resource.py, invenio_communities/members/services/request.py, invenio_communities/members/services/schemas.py, invenio_communities/members/services/service.py, invenio_communities/permissions.py, invenio_communities/templates/semantic-ui/invenio_communities/details/base.html, invenio_communities/templates/semantic-ui/invenio_communities/details/header.html, invenio_communities/views/communities.py, invenio_communities/webpack.py, setup.cfg, tests/communities/test_permissions.py, tests/conftest.py, tests/members/conftest.py, tests/members/test_members_notifications.py, tests/members/test_members_resource.py, tests/members/test_members_services.py
**This one**
- js+service: [#855] 4) integrate request flow with frontend [+]
This concludes the 2nd flow of the membership request feature.
Remaining flows are
- 'waiting for decision' flow
- 'making a decision' flow
This PR depends on: https://github.com/inveniosoftware/invenio-requests/pull/382 (well not directly but for full effect)
*Screencast*
[Screencast from 05-07-2024 02:16:56 PM.webm](https://github.com/inveniosoftware/invenio-communities/assets/1932651/1d9f1ab5-8115-47ef-a05f-d42357797add)
(Note: "Deleted User" is something I get locally even without any of my code changes from this and previous PRs. As such putting that aside)
**Previous ones**
- settings-ui: [#855] set membership policy
- header-ui: [#855] add inert request membership button+modal
- permissions: add …
=> [#855] 4) membership request flow frontend integration

.github/workflows/tests.yml, invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/InvitationsMembersModal.js
This will fix the editor's loss of content after losing focus in communities invite modal
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2771
Related to https://github.com/inveniosoftware/react-invenio-forms/pull/249
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contribu …
=> Editor: Update RichEditor to use inputValue

invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/RemovalReasonsSelect.js, invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js, invenio_communities/communities/resources/ui_schema.py, invenio_communities/members/resources/config.py
* closes https://github.com/zenodo/rdm-project/issues/598
=> http headers: use and adjust vnd.inveniordm.v1+json http accept header

invenio_communities/config.py
This PR fixes issue #1191
The defaults for COMMUNITIES_CUSTOM_FIELDS(_UI) should be lists, not dictionaries.
**Frontend**
**Reminder**
2. You agree that you have …
=> Incorrect defaults for COMMUNITIES_CUSTOM_FIELDS

invenio_communities/communities/resources/resource.py
* Return raw JSON instead of doing content negotiation for logo update responses.
=> resources: use default response handling for logo update

CHANGES.rst, invenio_communities/subcommunities/services/service.py
Until we are able to get the args properly we should remove them from the self link on the subcommunities endpoint
The remaining issue is shelved here https://github.com/inveniosoftware/invenio-communities/issues/1218 which is noted in the code
=> temp: remove args from self link

CHANGES.rst, invenio_communities/__init__.py, setup.cfg
Release fixes inveniosoftware/invenio-vocabularies#401
Bumping `invenio-communities` to a new major version since `invenio-vocabularies` is also being bumped to a major version with breaking changes (see inveniosoftware/invenio-vocabularies#405).
=> installation: bump invenio-vocabularies & 📦 release: v16.0.0

invenio_communities/subcommunities/resources/config.py
The header must be supported for subcommunity requests to work, otherwise the request fails due to unsupported accept header type. 
I am reverting it to the state that was before these [changes](https://github.com/inveniosoftware/invenio-communities/pull/1208/files).
=> subcommunities: revert resource config change

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemMobile.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/header/index.js, invenio_communities/assets/semantic-ui/js/invenio_communities/organizations/OrganizationsList.js, invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
> Added a component for Organizations using a popup to avoid clutter
**Frontend**
**Reminder**
2. You agree that you have …
=>  ui: added OrganizationsList component

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemMobile.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemMobile.js, invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current …
=> ui: added verify icon in community list

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
Use `community_ui` dict instead of `community` object in `button_to_request_membership` macro
**Frontend**
**Reminder** …
=> refactor: pass community_ui dict instead of community object

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js
Close https://github.com/inveniosoftware/invenio-rdm-records/issues/1805
Relies on https://github.com/inveniosoftware/react-invenio-forms/pull/255
Before:
After:
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-licen …
=> UI/UX: improve display of ROR information in select field

invenio_communities/administration/communities.py
Close [#2899](https://github.com/inveniosoftware/invenio-app-rdm/issues/2899)
Setting default_size and pagination_options as changing in invenio-search-ui would change it everywhere including non-admin pages
Removing `size` as it isn't an [accepted parameter](https://github.com/inveniosoftware/invenio-search-ui/blob/master/invenio_search_ui/searchconfig.py#L94) and therefore not used and `page=1` as this is the [default](https://github.com/inveniosoftware/invenio-search-ui/blob/master/invenio_search_ui/searchconfig.py#L87)
* If you have added [third-party code (copy/pasted or new …
=> admin: change default # of results from 10 to 20

invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/RecordResourceActions.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/RemovalReasonsSelect.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/RestoreConfirmation.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/TombstoneForm.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/search/filters/DeletionStatusFilter.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemMobile.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemMobile.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/labels/RestrictedLabel.js
When people copy and paste imports from other modules they might fail to update the location of the translations to the new module
[See all imports of i18next in invenio-communities](https://github.com/search?q=repo%3Ainveniosoftware%2Finvenio-communities+%22import+%7B+i18next+%7D%22&type=code)
This PR fixes the mistakes
**Frontend**
**Reminder**
By using …
=> chore: use local translations

invenio_communities/config.py, invenio_communities/templates/semantic-ui/invenio_communities/search.html, invenio_communities/views/decorators.py, invenio_communities/views/ui.py
Fixes: https://github.com/inveniosoftware/invenio-communities/issues/1209
=> communities: config: Update static page URLs to prevent name collisions

invenio_communities/communities/resources/config.py, invenio_communities/communities/services/service.py, invenio_communities/errors.py, invenio_communities/views/communities.py, invenio_communities/views/ui.py
Replacing generic error (FileNotFoundError was not imported from anywhere) with custom Invenio error
**Frontend**
**Reminder**
1. You license your contribution under …
=> config: add LogoNotFoundError

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js
* Fixes a bug where organizations selected from the search in the
profile form, should also submit the `id` so that it's linked to the
affiliation vocabulary entry.
=> settings-ui: fix organizations metadata payload

invenio_communities/notifications/builders.py, invenio_communities/subcommunities/services/request.py, invenio_communities/templates/semantic-ui/invenio_communities/details/new_subcommunity.html, invenio_communities/templates/semantic-ui/invenio_notifications/comment-subcommunity-invitation-request.create.jinja, invenio_communities/templates/semantic-ui/invenio_notifications/comment-subcommunity-request.create.jinja
Close https://github.com/inveniosoftware/invenio-requests/issues/417
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the current …
=> notifications: add comment notification for subcoms

invenio_communities/communities/records/mappings/os-v1/communities/communities-v2.0.0.json, invenio_communities/communities/records/mappings/os-v2/communities/communities-v2.0.0.json
* Closes https://github.com/inveniosoftware/invenio-communities/issues/1264
* Adds the missing `identifiers` property to parent communities.
=> mappings: add `identifiers` to parent organizations

CHANGES.rst, invenio_communities/__init__.py, invenio_communities/communities/schema.py
- **schema: skip unknown fields when loading organizations**
- **📦 release: v17.7.1**
=> skip unknown orgs

invenio_communities/members/services/request.py, invenio_communities/notifications/builders.py, invenio_communities/templates/semantic-ui/invenio_notifications/comment-community-invitation.create.jinja, invenio_communities/templates/semantic-ui/invenio_notifications/comment-community-request.create.jinja
close https://github.com/inveniosoftware/invenio-communities/issues/1261
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the current …
=> notifications: add comment notification for membership requests

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js
Partially closes: https://github.com/inveniosoftware/react-invenio-forms/issues/268
Depends On: https://github.com/inveniosoftware/react-invenio-forms/pull/269
**Frontend**
**Reminder**
1. You license your …
=> organizations: updated knownOrganizations to use id

invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/RecordResourceActions.js, invenio_communities/communities/services/config.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/322
Make consistent with the changes in https://github.com/inveniosoftware/invenio-administration/pull/234
=> administration: fix UI

invenio_communities/errors.py, invenio_communities/utils.py, tests/communities/test_resources.py
Update logo size limit error to show humanized byte size error on community image upload. Add helper function to perform this conversion.
**Frontend**
**Reminder**
1. You license your contribution under the same …
=> Humanize byte size error for community image upload

babel.ini, invenio_communities/communities/services/config.py
Currentlly when you run `python setup.py extract_messages` it will Not include `*.jinja` template files. 
This PR fix that.
**Frontend**
**Reminder**
1. You license …
=> i18n: Include `*.jinja` in `babel.ini` for Message Extraction

invenio_communities/communities/services/facets.py, invenio_communities/members/services/facets.py
This pull request fixes premature evaluation of i18n strings inside static fields. gettext call, that causes
the evaluation to be performed at boot time, was replaced with gettext_lazy that is performed at
request time. This fixes facet labels not being translated when language is changed.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-serv …
=> Using lazy_gettext in boot-time translations

invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/RestoreConfirmation.js, invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/TombstoneForm.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js, invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemMobile.js, invenio_communities/assets/semantic-ui/js/invenio_communities/organizations/OrganizationsList.js, invenio_communities/communities/schema.py, invenio_communities/communities/services/components.py, invenio_communities/communities/services/service.py, invenio_communities/members/resources/config.py, invenio_communities/members/services/components.py, invenio_communities/members/services/fields.py, invenio_communities/members/services/service.py, invenio_communities/roles.py, invenio_communities/subcommunities/services/schema.py, invenio_communities/subcommunities/services/service.py, invenio_communities/views/communities.py
mark strings for translation
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution …
=> i18n: mark translations for end user msgs

invenio_communities/communities/services/results.py
Sometimes, keys relevant to the serialization process are not included inside ``_source``, i.e. "highlight." By adding ``hit.meta`` as part of the serializer context, we make them available without the risk of name collision.
=> services: include Opensearch meta in the results

CHANGES.rst, invenio_communities/__init__.py, invenio_communities/webpack.py, setup.cfg
related to https://github.com/inveniosoftware/invenio-search-ui/pull/215
**Frontend**
**Reminder**
2. You agree that you …
=> Fix-axios-version

invenio_communities/templates/semantic-ui/invenio_communities/details/about/index.html, invenio_communities/templates/semantic-ui/invenio_communities/details/curation_policy/index.html, invenio_communities/templates/semantic-ui/invenio_communities/details/header.html, invenio_communities/templates/semantic-ui/invenio_communities/details/members/base.html, invenio_communities/templates/semantic-ui/invenio_communities/details/members/invitations.html, invenio_communities/templates/semantic-ui/invenio_communities/details/members/members.html, invenio_communities/templates/semantic-ui/invenio_communities/details/requests/index.html, invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html, invenio_communities/templates/semantic-ui/invenio_communities/details/settings/pages.html, invenio_communities/templates/semantic-ui/invenio_communities/details/settings/privileges.html, invenio_communities/templates/semantic-ui/invenio_communities/details/settings/submission_policy.html, invenio_communities/templates/semantic-ui/invenio_communities/details/subcommunity/index.html, invenio_communities/views/communities.py
* the variable name in communities_requests is community and not
community_ui
=> fix: rename variable

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
The "Request membership" button would show up for superusers. This disables it completely until we revisit the implementation.
=> membership-request [#855]: disable button until feature fully merged [+]

docs/conf.py, invenio_communities/alembic/72b37bb4119c_create_indeces_for_bucket_id.py, invenio_communities/errors.py, invenio_communities/ext.py, invenio_communities/members/services/service.py, invenio_communities/requests/user_moderation/actions.py, invenio_communities/subcommunities/resources/config.py, invenio_communities/subcommunities/resources/resource.py, invenio_communities/subcommunities/services/service.py, tests/communities/test_alembic.py, tests/members/conftest.py, tests/members/test_members_resource.py
- **chore: remove unused imports**
- **subcomunities: fix parent community ID referencing in request payload**
* Instead of using the passed argument community ID (which could be a
slug), use the resolved parent community object to reference in the
request creation.
=> Fix subcommunity request parent ID reference

invenio_communities/assets/semantic-ui/js/invenio_communities/subcommunity/new.js
If the value is not present, the form will not render breaking here https://github.com/inveniosoftware/invenio-communities/blob/master/invenio_communities/assets/semantic-ui/js/invenio_communities/subcommunity/new.js#L38
=> js: add slug to subcommunity initial values

invenio_communities/views/ui.py
Closes #1323 
Previously, we only handled the `PermissionDeniedError` which is a subclass of `PermissionDenied`, and a sibling of `RecordPermissionDeniedError` (which was unhandled).
Since we want to handle both permission denied errors the same, we just register a handler for the parent exception class here.
=> fix(views): handle permission denied error in the UI view functions
