inveniosoftware/invenio-communities

invenio_communities/admin/__init__.py
invenio_communities/bundles.py
invenio_communities/forms.py
invenio_communities/models.py
invenio_communities/tasks.py
invenio_communities/upgrades/communities_2014_03_07_ranker.py
invenio_communities/upgrades/communities_2014_10_17_featured_communities.py
invenio_communities/views.py
requirements-devel.txt
setup.cfg
setup.py
tests/test_communities.py
tests/test_featured_community.py
tests/test_views.py

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

installation: fix invenio_utils, invenio_ext imports

---

.editorconfig
invenio_communities/config.py
invenio_communities/ext.py
invenio_communities/models.py
invenio_communities/receivers.py
invenio_communities/utils.py
invenio_communities/views.py
setup.py
tests/conftest.py
tests/test_invenio_communities.py

* Adds community creation signal and integrates with OAI-PMH sets.

global: addition of community creation signal

---

.travis.yml
invenio_communities/cli.py
invenio_communities/config.py
invenio_communities/models.py
invenio_communities/receivers.py
invenio_communities/utils.py
invenio_communities/views.py
setup.py

Depends on PR https://github.com/inveniosoftware/invenio-communities/pull/17

global: addition of bucket-based logo storage

---

invenio_communities/config.py
invenio_communities/receivers.py
tests/conftest.py

* Fixes missing parameters for function.

receivers: arguments fix

---

.travis.yml
CHANGES.rst
RELEASE-NOTES.rst
invenio_communities/version.py

release: v1.0.0a1

---

invenio_communities/bundles.py
invenio_communities/templates/invenio_communities/new.html

* Adds CKEditor support back. (closes #24)

bundles: ckeditor support

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_communities/models.py
invenio_communities/version.py
tests/test_invenio_communities.py

release: v1.0.0a2

---

invenio_communities/cli.py
invenio_communities/ext.py
invenio_communities/serializers/__init__.py
invenio_communities/serializers/response.py
invenio_communities/serializers/schemas/__init__.py
invenio_communities/serializers/schemas/community.py
invenio_communities/views/__init__.py
invenio_communities/views/api.py
invenio_communities/views/ui.py
setup.py
tests/conftest.py
tests/no_test_cli.py
tests/test_invenio_communities.py

* Addition of REST methods to retrieve communities information.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

REST: addition of communities information rest

---

invenio_communities/cli.py
invenio_communities/ext.py
invenio_communities/serializers/__init__.py
invenio_communities/serializers/response.py
invenio_communities/serializers/schemas/__init__.py
invenio_communities/serializers/schemas/community.py
invenio_communities/views/__init__.py
invenio_communities/views/api.py
invenio_communities/views/ui.py
setup.py
tests/conftest.py
tests/no_test_cli.py
tests/test_invenio_communities.py

global: app initialization

---

invenio_communities/serializers/__init__.py
invenio_communities/serializers/response.py
invenio_communities/serializers/schemas/community.py
invenio_communities/views/api.py
setup.py
tests/test_invenio_communities.py

* Adds Elasticsearch like envelope of search results.
* Adds JSON pretty printing for browser API requests.

rest: collection serialization

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_communities/version.py

release: v1.0.0a3

---

invenio_communities/version.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

version: post-release bump

---

invenio_communities/config.py
invenio_communities/links.py
invenio_communities/serializers/response.py
invenio_communities/serializers/schemas/community.py
invenio_communities/views/api.py
tests/test_invenio_communities.py

* Adds the link to the view part of each community. (closes #39)
* Adds links in the resultant JSON to the pagination.
* Adds links to the response headers to the pagination.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

rest: addition of links

---

tests/conftest.py
tests/test_invenio_communities.py
tests/test_tasks.py
tests/test_utils.py

* Refactorizes the tests in order to use the conftest fixtures.
(closes #40)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

tests: fixtures refactoring

---

.travis.yml

travis: reenable lowest and release requirements

---

invenio_communities/cli.py

- fix add record in a community

cli: fix add record

---

CHANGES.rst
RELEASE-NOTES.rst
docs/conf.py
invenio_communities/models.py
invenio_communities/version.py

* InclusionRequest.get returns None on fail.

global: inclusion request api change

---

docs/api.rst
setup.py
tests/conftest.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

docs: removal of undoc-members

---

.travis.yml
.tx/config
invenio_communities/forms.py
invenio_communities/translations/da/LC_MESSAGES/messages.po
invenio_communities/translations/es/LC_MESSAGES/messages.po
invenio_communities/translations/fr/LC_MESSAGES/messages.po
invenio_communities/translations/it/LC_MESSAGES/messages.po
invenio_communities/translations/messages.pot

Signed-off-by: Alizee Pace <alizee.pace@gmail.com>

i18n: tx configuration fix

---

invenio_communities/models.py
invenio_communities/templates/invenio_communities/portalbox_upload.html

Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>

global: addition of upload URL

---

invenio_communities/config.py
invenio_communities/forms.py
invenio_communities/utils.py
invenio_communities/views/ui.py

* Adds logo size passing to ObjectVersion.
* Enables SVG support.

global: logo file size fix

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_communities/version.py

release: v1.0.0a11

---

.tx/config
setup.py

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

i18n: tx canonical slug

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_communities/models.py
invenio_communities/version.py
setup.py
tests/conftest.py
tests/test_invenio_communities.py

Requires https://github.com/inveniosoftware/invenio-communities/pull/76 and travis restart

release: v1.0.0a12

---

.editorconfig
.travis.yml
MANIFEST.in
examples/app.py
invenio_communities/alembic/21e13cb1eff2_create_communities_branch.py
invenio_communities/alembic/2d9884d0e3fa_create_community_tables.py
setup.py
tests/conftest.py
tests/test_invenio_communities.py
tests/test_utils.py

Depends on inveniosoftware/invenio-db#59, inveniosoftware/invenio-accounts#172, inveniosoftware/invenio-records#158

global: initial alembic recipes

---

invenio_communities/models.py
setup.py
tests/conftest.py
tests/test_models.py

Made text search case insensitive and matches word instead of substring.
Added test cases to test filter_community function in Community class.
#99

Text search: case insensitive search

---

invenio_communities/templates/invenio_communities/index.html

* Typo fix in index.html
Solves https://github.com/zenodo/zenodo/issues/998

templates: typo fix

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_communities/serializers/schemas/community.py
invenio_communities/version.py
invenio_communities/views/api.py
setup.cfg

api: addition of community created updated timestamps

---

invenio_communities/templates/invenio_communities/index.html
invenio_communities/templates/invenio_communities/new.html

Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>

views: new community form action fix

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_communities/version.py

release: v1.0.0a17

---

examples/app.py
invenio_communities/templates/invenio_communities/new.html

* new.html : Removes typo
* app.py : Fixes blueprints loading

templates: Fixes bug in the community details temp

---

CHANGES.rst
invenio_communities/version.py

release: v2.0.3

---

invenio_communities/assets/semantic-ui/js/invenio_communities/records_search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/search.js
invenio_communities/assets/semantic-ui/scss/invenio_communities/theme.scss
invenio_communities/templates/semantic-ui/invenio_communities/header.html

* Fixes header search bar in search and records search
* Fixes community padding from header
closes #167

fix various styling issues

---

CHANGES.rst
invenio_communities/assets/semantic-ui/js/invenio_communities/records_search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/search.js
invenio_communities/version.py

Based on https://github.com/inveniosoftware/invenio-theme/pull/180

theme: set search button class

---

invenio_communities/assets/semantic-ui/scss/invenio_communities/theme.scss
invenio_communities/templates/semantic-ui/invenio_communities/settings.html

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/248

styles: Fix header and footer

---

CHANGES.rst
invenio_communities/signals.py
invenio_communities/version.py
invenio_communities/views/ui.py

*Flash message is now hanlded by the signal receiver

ui: adds signal on community creation

---

invenio_communities/communities/components.py
invenio_communities/communities/records/api.py
invenio_communities/communities/records/providers.py
invenio_communities/communities/service_config.py

global: adds custom PID generation and updating

---

invenio_communities/communities/components.py
invenio_communities/communities/records/api.py
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/v6/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json
invenio_communities/communities/records/providers.py
invenio_communities/communities/records/systemfields/access.py
invenio_communities/communities/schema.py
invenio_communities/communities/service_config.py
invenio_communities/ext.py
tests/communities/conftest.py

Add "access" field

---

invenio_communities/communities/components.py
invenio_communities/communities/permissions.py
invenio_communities/communities/records/systemfields/access.py
invenio_communities/communities/resource.py
invenio_communities/communities/resource_config.py
invenio_communities/communities/service.py
invenio_communities/communities/service_config.py
invenio_communities/ext.py
invenio_communities/views/__init__.py
invenio_communities/views/api.py
setup.py

* Addresses https://github.com/inveniosoftware/invenio-communities/issues/235

resources: adds renaming community ID endpoint

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/RenameCommunityButton.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/assets/semantic-ui/less/invenio_communities/theme.less
invenio_communities/communities/schema.py
invenio_communities/config.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/privileges.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/profile.html
invenio_communities/views/communities.py
invenio_communities/views/ui.py
invenio_communities/webpack.py

* Various UX fixes
closes #228

communities: add settings/privileges tab

---

invenio_communities/assets/semantic-ui/js/invenio_communities/new.js
invenio_communities/assets/semantic-ui/less/invenio_communities/theme.less
invenio_communities/communities/schema.py
invenio_communities/templates/semantic-ui/invenio_communities/new.html
invenio_communities/views/communities.py

communities: add creation page

---

invenio_communities/communities/records/models.py

models: refactors Community table

---

.gitignore
invenio_communities/communities/schema.py
invenio_communities/communities/services/config.py
tests/communities/conftest.py
tests/communities/test_resources.py

tests REST API community resources

---

invenio_communities/communities/__init__.py
invenio_communities/communities/records/api.py
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/models.py
invenio_communities/communities/resources/__init__.py
invenio_communities/communities/resources/config.py
invenio_communities/communities/resources/resource.py
invenio_communities/communities/services/__init__.py
invenio_communities/communities/services/config.py
invenio_communities/communities/services/service.py
invenio_communities/ext.py
setup.py
tests/communities/conftest.py
tests/communities/test_resources.py

global: files support

---

invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/systemfields/access.py
invenio_communities/communities/schema.py
invenio_communities/communities/services/permissions.py
invenio_communities/views/communities.py
tests/communities/test_resources.py

global: rename visibility value from 'public' to 'restricted'

---

invenio_communities/assets/semantic-ui/js/invenio_communities/frontpage.js
invenio_communities/assets/semantic-ui/js/invenio_communities/new.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/DeleteButton.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/RenameCommunityButton.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/assets/semantic-ui/less/invenio_communities/theme.less
invenio_communities/communities/services/config.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/profile.html
invenio_communities/views/communities.py
invenio_communities/views/decorators.py

communities: add logo uploader and other fixies

---

README.rst
invenio_communities/communities/records/systemfields/access.py
tests/communities/test_resources.py

access: add missing member/record policy

---

invenio_communities/assets/semantic-ui/js/invenio_communities/new.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/communities/services/config.py

communities: add dropzone config

---

invenio_communities/assets/semantic-ui/js/invenio_communities/frontpage.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js
invenio_communities/communities/services/permissions.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/tombstone.html
invenio_communities/views/communities.py
invenio_communities/views/ui.py

closes #271 #253 
* Adds tombstone page
* Registers UI error handlers for PID errors

permissions: add permission to UI views

---

invenio_communities/assets/semantic-ui/js/invenio_communities/frontpage.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/assets/semantic-ui/less/invenio_communities/theme.less
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html

Default comm logo

---

invenio_communities/assets/semantic-ui/js/invenio_communities/new.js
invenio_communities/assets/semantic-ui/less/invenio_communities/theme.less
invenio_communities/templates/semantic-ui/invenio_communities/new.html

communities: add top level error message

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/DeleteButton.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/RenameCommunityButton.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js

communities: add validation message on rename

---

.github/workflows/pypi-publish.yml
invenio_communities/views/ui.py

views: plus-menu

---

invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html
invenio_communities/views/communities.py
invenio_communities/views/decorators.py

settings: fix permissions on settings endpoint

---

invenio_communities/config.py
invenio_communities/views/api.py
invenio_communities/views/ui.py

config: enable/disable communities

---

invenio_communities/communities/services/components.py
invenio_communities/communities/services/service.py
tests/communities/conftest.py
tests/communities/test_resources.py

components: validates PID value on creation and renaming

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js

Remove unused fields from settings

---

invenio_communities/assets/semantic-ui/js/invenio_communities/search.js
invenio_communities/templates/semantic-ui/invenio_communities/search.html

communities-search: add tmp config for type facet labels

---

invenio_communities/assets/semantic-ui/js/invenio_communities/search.js
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html
invenio_communities/templates/semantic-ui/invenio_communities/search.html

Align css settings

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/assets/semantic-ui/less/invenio_communities/theme.less
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

Details page info

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/v6/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json
invenio_communities/communities/schema.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/views/communities.py
tests/communities/conftest.py
tests/communities/test_resources.py

closes #286 
- Human readable types in community page
- Some small fixes in community page

communities: rename affiliations to organizations

---

invenio_communities/cli.py
invenio_communities/communities/services/components.py
invenio_communities/communities/services/permissions.py
invenio_communities/fixtures/__init__.py
invenio_communities/fixtures/demo.py
invenio_communities/fixtures/tasks.py
invenio_communities/views/api.py
invenio_communities/views/decorators.py
invenio_communities/views/ui.py
setup.py
tests/communities/test_cli.py

fixtures: demo communities creation

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members.js
invenio_communities/assets/semantic-ui/js/invenio_communities/new.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/RenameCommunityButton.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js

closes https://github.com/inveniosoftware/invenio-communities/issues/240

Fix validation messages

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js
invenio_communities/assets/semantic-ui/less/invenio_communities/theme.less
invenio_communities/views/communities.py

closes https://github.com/inveniosoftware/invenio-communities/issues/283

communities-privileges: use radio buttons instead of dropdowns

---

invenio_communities/templates/semantic-ui/invenio_communities/details/index.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html
invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html
invenio_communities/templates/semantic-ui/invenio_communities/new.html
invenio_communities/templates/semantic-ui/invenio_communities/search.html

views: add title tags

---

CHANGES.rst
invenio_communities/assets/semantic-ui/js/invenio_communities/new.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js
invenio_communities/communities/services/components.py
invenio_communities/communities/services/service.py
invenio_communities/version.py
tests/communities/test_resources.py

Form error handling

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/RenameCommunityButton.js

ui: fixes redirect after rename

---

CHANGES.rst
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/RenameCommunityButton.js
invenio_communities/version.py

communities-rename: fix wrong form submission

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js

ul: provides visual feedback when changing permissions

---

invenio_communities/communities/services/config.py
invenio_communities/templates/semantic-ui/invenio_communities/details/search.html
invenio_communities/templates/semantic-ui/invenio_communities/search.html
invenio_communities/version.py
setup.py

closes inveniosoftware/invenio-app-rdm#833

services: align facets with records-resources

---

invenio_communities/cli.py
invenio_communities/version.py

partially closes https://github.com/inveniosoftware/invenio-rdm-records/issues/636

cli: implement rebuild index function

---

invenio_communities/communities/records/api.py
setup.py

Pretty analogous to https://github.com/inveniosoftware/invenio-drafts-resources/pull/168
Since it's a dependency, also needs the changes here to work with Flask 2.x: https://github.com/inveniosoftware/invenio-rdm-records/pull/823

Make package ready for Flask 2.x

---

docs/conf.py
invenio_communities/__init__.py
invenio_communities/communities/records/api.py
invenio_communities/communities/records/mappings/__init__.py
invenio_communities/communities/records/mappings/v6/__init__.py
invenio_communities/communities/records/mappings/v7/__init__.py
invenio_communities/communities/records/models.py
invenio_communities/communities/records/providers.py
invenio_communities/config.py
invenio_communities/proxies.py
invenio_communities/token.py
invenio_communities/utils.py
invenio_communities/webpack.py
setup.py
tests/members/test_members_views.py

global: remove python 2 support

---

invenio_communities/communities/resources/resource.py
invenio_communities/communities/services/service.py
invenio_communities/version.py
setup.py

- services: order methods to pass identity first
- release: v2.7.0.dev2

258 bump records resources for method parameters order

---

invenio_communities/requests/resolver.py
invenio_communities/version.py
setup.py
tests/communities/alembic/test_alembic.py

requires/required by: https://github.com/inveniosoftware/invenio-requests/pull/103 and https://github.com/inveniosoftware/invenio-records-resources/pull/296

requests: fix imports according to requests refactoring

---

invenio_communities/assets/semantic-ui/js/invenio_communities/api.js
invenio_communities/communities/services/config.py
invenio_communities/communities/services/facets.py
invenio_communities/config.py
setup.py
tests/communities/alembic/test_alembic.py

api: refactor facets definition

---

invenio_communities/alembic/a0f01ee61a5f_create_communities_members_table.py
invenio_communities/invitations/services/actions.py
invenio_communities/members/records/api.py
invenio_communities/members/records/mappings/__init__.py
invenio_communities/members/records/mappings/v6/__init__.py
invenio_communities/members/records/mappings/v6/communitymembers/members-v1.0.0.json
invenio_communities/members/records/mappings/v7/__init__.py
invenio_communities/members/records/mappings/v7/communitymembers/members-v1.0.0.json
invenio_communities/members/records/models.py
invenio_communities/members/resources/__init__.py
invenio_communities/members/resources/config.py
invenio_communities/members/resources/resource.py
invenio_communities/members/services/__init__.py
invenio_communities/members/services/config.py
invenio_communities/members/services/permissions.py
invenio_communities/members/services/schema.py
setup.py
tests/communities/alembic/test_alembic.py
tests/memberships/test_membership_services.py

- memberships: add id as primary key
- closes #382

382 membership id

---

invenio_communities/alembic/a0f01ee61a5f_create_communities_members_table.py
invenio_communities/invitations/services/__init__.py
invenio_communities/invitations/services/request_types.py
invenio_communities/invitations/services/schemas.py
invenio_communities/members/__init__.py
invenio_communities/members/records/api.py
invenio_communities/members/records/mappings/v6/community_members/members-v1.0.0.json
invenio_communities/members/records/mappings/v7/community_members/members-v1.0.0.json
invenio_communities/members/records/models.py
invenio_communities/members/services/__init__.py
invenio_communities/members/services/schema.py
invenio_communities/members/services/service.py
tests/memberships/test_membership_services.py

- memberships: invite user with role to community
- closes #381

381 invite user with role

---

invenio_communities/assets/semantic-ui/less/invenio_communities/theme.less
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

part of https://github.com/inveniosoftware/invenio-app-rdm/pull/1258

details: add new upload button

---

invenio_communities/communities/services/facets.py

closes https://github.com/inveniosoftware/invenio-communities/issues/403

facets: add label for restricted visibility

---

invenio_communities/alembic/f701a32e6fbe_create_communities_members_table.py
invenio_communities/invitations/__init__.py
invenio_communities/invitations/errors.py
invenio_communities/invitations/services/__init__.py
invenio_communities/invitations/services/common.py
invenio_communities/invitations/services/permissions.py
invenio_communities/invitations/services/request_types.py
invenio_communities/invitations/services/service.py
invenio_communities/members/records/models.py
invenio_communities/members/services/service.py
invenio_communities/permissions.py
setup.py
tests/memberships/conftest.py
tests/memberships/test_invitations_permissions.py
tests/memberships/test_invitations_rules.py
tests/memberships/test_members_permissions.py
tests/memberships/test_membership_services.py

- depends on https://github.com/inveniosoftware/invenio-requests/pull/136 being released
- closes #391

391 invitation permissions

---

invenio_communities/assets/semantic-ui/js/invenio_communities/new.js

* closes: inveniosoftware/invenio-communities#404

Community creation: add barcode to identifier label

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js

* closes https://github.com/inveniosoftware/invenio-communities/issues/405

communitySettings: Allow type to be removed

---

invenio_communities/views/communities.py
invenio_communities/views/decorators.py

* closes https://github.com/inveniosoftware/invenio-communities/issues/329

privilegesPage: fix missing community logo

---

invenio_communities/version.py

- releasing v0.2.7.dev7
- will merge and release immediately as this is a temporary hotfix

release: v2.7.0.dev7

---

invenio_communities/assets/semantic-ui/less/invenio_communities/theme.less
invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html
invenio_communities/templates/semantic-ui/invenio_communities/search.html

* closes #439
Not very nice, better than current, facets are missing at the moment...

search: fix header

---

invenio_communities/assets/semantic-ui/js/invenio_communities/frontpage.js
invenio_communities/assets/semantic-ui/js/invenio_communities/search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/search/components.js
invenio_communities/assets/semantic-ui/js/invenio_communities/search/index.js
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/details/index.html
invenio_communities/webpack.py

Ensure html markup of the description is displayed in the community details page.
Ensure html markup of the description is displayed in the communities frontpage.
* closes: inveniosoftware/invenio-communities#401
* closes: inveniosoftware/invenio-app-rdm#1280

Community view: truncate community description to 2 lines

---

invenio_communities/config.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/details/members.html
invenio_communities/views/communities.py
invenio_communities/views/ui.py
invenio_communities/webpack.py

Created the members tab for the community details page
- added the members view
- edited the members template
- added the js entrypoint for members
closes https://github.com/inveniosoftware/invenio-communities/issues/450

 communities: add the members tab 

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/searchBarWithFilters.js

members: add searchbar with filters

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ErrorPopup.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SearchBarWithFilters.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationActionButtons.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItemWithState.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsResults.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsResultsContainer.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchBarElement.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchLayout.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/mock.js
invenio_communities/assets/semantic-ui/translations/invenio_communities/messages/en/translations.json
invenio_communities/templates/semantic-ui/invenio_communities/details/members/invitations.html

- structured the folders
- created the invitations list
closes https://github.com/inveniosoftware/invenio-communities/issues/451
needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1399 for some styling additions

invitations: add invitations list

---

invenio_communities/communities/services/service.py
tests/communities/test_resources.py

service: fix permission on logo delete

---

invenio_communities/assets/semantic-ui/js/invenio_communities/api/GroupsApi.js
invenio_communities/assets/semantic-ui/js/invenio_communities/api/UsersApi.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ErrorMessage.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchLayout.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/GroupTabPane.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/InvitationsMembersModal.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MemberSearchBar.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/PeopleTabPane.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/SelectedMembers.js
invenio_communities/assets/semantic-ui/translations/invenio_communities/package.json
invenio_communities/config.py
invenio_communities/permissions.py
invenio_communities/templates/semantic-ui/invenio_communities/details/members/invitations.html
invenio_communities/views/communities.py

- closes https://github.com/inveniosoftware/invenio-communities/issues/493
- needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1423

members: add invitation modal

---

invenio_communities/members/services/service.py
tests/members/test_members_services.py

requires https://github.com/inveniosoftware/invenio-records-resources/pull/320

invitation: refresh index after inviting

---

invenio_communities/assets/semantic-ui/js/invenio_communities/api/config.js
invenio_communities/assets/semantic-ui/js/invenio_communities/api/invitations/api.js
invenio_communities/assets/semantic-ui/js/invenio_communities/api/members/api.js
invenio_communities/assets/semantic-ui/js/invenio_communities/api/serializers.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ActionDropdown.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ErrorMessage.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/RemoveMemberModal.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SearchResultsBulkActions.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SelectedMembers.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/modal_manager/ModalContextProvider.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/modal_manager/context.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/modal_manager/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/GroupTabPane.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MembersWithRoleSelection.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/components/MembersResult.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMemberBulkActions.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/member_view/index.js
invenio_communities/config.py
invenio_communities/members/services/schemas.py
invenio_communities/templates/semantic-ui/invenio_communities/details/members/members.html

- added modal for removing a member or leaving a community
- added a modal context for managing the modals
- continued comments left to do on this PR https://github.com/inveniosoftware/invenio-communities/pull/526
closes https://github.com/inveniosoftware/invenio-communities/issues/488

members: add leave community modal

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ActionDropdown.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/RadioSelection.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SelectedMembers.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/permissions.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/dropdowns.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchLayout.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MemberSearchBar.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MembersWithRoleSelection.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMemberBulkActions.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js
invenio_communities/config.py
invenio_communities/roles.py

closes https://github.com/inveniosoftware/invenio-communities/issues/534
closes https://github.com/inveniosoftware/invenio-communities/issues/538

roles: make the roles config order sensitive

---

invenio_communities/alembic/5b478fe7ef7f_create_featured_communities_table.py
invenio_communities/communities/dumpers/featured.py
invenio_communities/communities/records/api.py
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/jsonschemas/communities/definitions-v2.0.0.json
invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json
invenio_communities/communities/records/models.py
invenio_communities/communities/resources/config.py
invenio_communities/communities/resources/resource.py
invenio_communities/communities/schema.py
invenio_communities/communities/services/components.py
invenio_communities/communities/services/config.py
invenio_communities/communities/services/results.py
invenio_communities/communities/services/service.py
invenio_communities/communities/services/uow.py
invenio_communities/errors.py
invenio_communities/fixtures/tasks.py
invenio_communities/permissions.py
tests/communities/test_alembic.py
tests/communities/test_services.py

closes #497 
Adds featured community functionalities.
**Reminder**
2. You agree that you have the right …

feature: add featured communities

---

invenio_communities/communities/services/components.py
invenio_communities/communities/services/config.py
setup.cfg
tests/communities/test_components.py

closes #474 
relies on https://github.com/inveniosoftware/invenio-rdm-records/pull/928 (for the `search_pattern` to work as the `communities` field is missing in the `parent` from the current mapping)
Add OAI set component for communities. It should create/update/delete sets for communities accordingly.
**Reminder** …

feature: add OAI set component

---

invenio_communities/assets/semantic-ui/js/invenio_communities/api/members/api.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMemberBulkActions.js

closes https://github.com/inveniosoftware/invenio-communities/issues/549

bulk actions: add bulk remove users

---

invenio_communities/views/communities.py

closes: inveniosoftware/invenio-communities#548

Views: internationalize vocabularies

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/views/ui.py

closes: inveniosoftware/invenio-communities#408

Communities menu: use flask menu to generate communities menu

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/communities/records/api.py
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json
invenio_communities/communities/schema.py
invenio_communities/communities/services/config.py
invenio_communities/fixtures/demo.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/profile.html
invenio_communities/views/communities.py
tests/communities/conftest.py
tests/communities/test_cli.py
tests/communities/test_relations_organizations.py
tests/communities/test_relations_types.py
tests/communities/test_resources.py
tests/conftest.py

- requires https://github.com/inveniosoftware/invenio-vocabularies/pull/187
- closes https://github.com/inveniosoftware/invenio-communities/issues/500
- closes https://github.com/inveniosoftware/invenio-communities/issues/501
**Reminder** …

Communities relations

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/frontpage.js

Closes https://github.com/inveniosoftware/invenio-communities/issues/562

communities: make list responsive

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js

Closes https://github.com/inveniosoftware/invenio-communities/issues/571

search: add responsive sidebar

---

invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js

Closes https://github.com/inveniosoftware/invenio-communities/issues/563
Uses styling classes for `.item.community-item` added in https://github.com/inveniosoftware/invenio-app-rdm/pull/1496

requests: Add responsive layout

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js
invenio_communities/templates/semantic-ui/invenio_communities/details/base.html
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/details/members/base.html
invenio_communities/templates/semantic-ui/invenio_communities/details/members/invitations.html
invenio_communities/templates/semantic-ui/invenio_communities/details/members/members.html
invenio_communities/templates/semantic-ui/invenio_communities/details/requests/index.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/privileges.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/profile.html

* requests search results details url changed to
based
* refactor submenus
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1474

requests: change details URL to community based

---

invenio_communities/communities/services/service.py
invenio_communities/generators.py
tests/communities/test_services.py
tests/conftest.py
tests/members/conftest.py

search: return communities a user is member of via search_user_communities

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/frontpage.js
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

Align new upload button

---

invenio_communities/members/records/mappings/v7/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/v7/communitymembers/members/member-v1.0.0.json
invenio_communities/members/services/config.py
tests/members/test_members_resource.py

- closes https://github.com/inveniosoftware/invenio-communities/issues/509
Missing more in depth tests.

members: add sort by name

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/webpack.py

- requires https://github.com/inveniosoftware/invenio-communities/pull/531 Otherwise the `funding` relation is not going to be denormalised and the UI won't render funders/awards properly.
- requires https://github.com/inveniosoftware/react-invenio-deposit/pull/465 being released. Otherwise the component will not be found. 
- closes https://github.com/inveniosoftware/invenio-communities/issues/587
this PR adds `FundingField` to community settings.

communities: added funding to community settings.

---

invenio_communities/assets/semantic-ui/js/invenio_communities/api/invitations/api.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js

Add appropriate data to invitations table.
closes: #537

Invitations: replace mockup updates by use of the services

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/Filters.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/FilterLabel.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SearchBarWithFilters.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchLayout.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/components/MembersSearchLayout.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/index.js

* Fix display of boolean visibility label
* closes https://github.com/inveniosoftware/invenio-communities/issues/459
* closes https://github.com/inveniosoftware/invenio-communities/issues/588

members: add static filters to searchbar

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/MembersSearchBarElement.js

Searchbar now correctly triggers a search on the wanted events.
closes https://github.com/inveniosoftware/invenio-communities/issues/585

members: fix searchbar

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js

- requires https://github.com/inveniosoftware/invenio-rdm-records/pull/962
- closes https://github.com/inveniosoftware/invenio-communities/issues/619
These lines seem to have been removed in some rebase :/ but is working now!
https://user-images.githubusercontent.com/6756943/167429896-d5cee4e1-038b-4aad-8f81-833889977b5b.mov

ui: fix funding deserialization

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/new.js

Closes https://github.com/inveniosoftware/invenio-communities/issues/613

new community: disable submit on enter on text fields

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SelectedMembers.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MemberSearchBar.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/public_view/PublicMembersResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/communities/resolver.py
invenio_communities/members/services/request.py
invenio_communities/members/services/schemas.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/profile.html
invenio_communities/views/communities.py
invenio_communities/views/decorators.py

Requires: https://github.com/inveniosoftware/invenio-requests/pull/209

global: fixes to community logo

---

invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js

community-requests: fix receiver param

---

invenio_communities/communities/resources/config.py
invenio_communities/communities/resources/resource.py
invenio_communities/communities/services/config.py
invenio_communities/communities/services/service.py
invenio_communities/templates/semantic-ui/invenio_communities/details/requests/index.html
tests/communities/test_services.py

communities: add community requests endpoint

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SearchBarWithFilters.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SearchDropdowns.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchBarElement.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchLayout.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/member_view/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/public_view/index.js

* fix invitations searchbar
* fix community public view
* closes #589
* closes #594

members: fix sorting options

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1525
**Needs PR** https://github.com/inveniosoftware/invenio-app-rdm/pull/1544 <<--- More details + screenshots

facets-sidebar: fix inconsistencies in layout

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/new.js

Closes https://github.com/inveniosoftware/invenio-communities/issues/628
**Needs PR** https://github.com/inveniosoftware/react-invenio-forms/pull/135
- Updating slug value onChange
https://user-images.githubusercontent.com/21052053/167636455-8f426f31-6fc6-4007-8a14-d5f8a5c01c1a.mov

new community: update slug on change

---

invenio_communities/assets/semantic-ui/js/invenio_communities/api/invitations/api.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchLayout.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/GroupTabPane.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/InvitationsMembersModal.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MemberSearchBar.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MembersWithRoleSelection.js
invenio_communities/assets/semantic-ui/js/invenio_communities/routes/appUrls.js
invenio_communities/members/records/api.py
invenio_communities/members/records/mappings/v7/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/v7/communitymembers/members/member-v1.0.0.json
invenio_communities/members/resources/resource.py
invenio_communities/members/services/schemas.py
invenio_communities/members/services/service.py
invenio_communities/webpack.py

* mappings: change community mapping description field
* schemas: add group member avatar to community member
* ui: implement frontend url generator
* closes #611

members: fix group add workflow

---

invenio_communities/__init__.py

release: v2.8.0.dev24

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MemberSearchBar.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js

* restrict changing member visibility to public
immediately after changing to hidden
* closes #649

members: dont restrict options on search

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/new.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/communities/schema.py
tests/communities/test_resources.py

* allow updating the community resource
with non empty Vocabulary field
* closes #655

community: fix community form error

---

invenio_communities/__init__.py
invenio_communities/members/services/service.py
setup.cfg

- requires https://github.com/inveniosoftware/invenio-records-resources/pull/339
- closes https://github.com/inveniosoftware/invenio-communities/issues/620

members: adapt index refresh op to new api

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchLayout.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/InvitationsMembersModal.js
invenio_communities/config.py
invenio_communities/generators.py
invenio_communities/permissions.py
invenio_communities/templates/semantic-ui/invenio_communities/details/members/invitations.html
tests/members/test_members_no_groups.py

Ensure the above mentioned flag is enable when adding members in the backend.
closes: #627
Testing of the workflow of inviting a user.

Members invitations: rename COMMUNITIES_ALLOW_GROUP_INVITES flag

---

invenio_communities/config.py
invenio_communities/roles.py

roles: support curate and view actions for roles

---

invenio_communities/communities/services/facets.py
invenio_communities/config.py

closes: [#1572](https://github.com/inveniosoftware/invenio-app-rdm/issues/1572)

Communities: fix search facets

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ActionDropdown.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/dropdowns.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js

Fix mobile UI issues
closes: [#661](https://github.com/inveniosoftware/invenio-communities/issues/661)
closes: https://github.com/inveniosoftware/invenio-communities/issues/646
depends on: https://github.com/inveniosoftware/invenio-app-rdm/pull/1598

Members: add responsive layout to tablet resolution [DEPENDS ON: https://github.com/inveniosoftware/invenio-app-rdm/pull/1598]

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

Closes https://github.com/inveniosoftware/invenio-theme/issues/286
Added `.trigger` to accordion panel

header: add trigger class to accordion panel

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MemberSearchBar.js

closes [inveniosoftware/invenio-app-rdm/#1599](https://github.com/inveniosoftware/invenio-app-rdm/issues/1599)
allows multiple selection on invitation dropdown
selection only happens on enter/click
https://user-images.githubusercontent.com/72449192/168861392-c30a0226-53eb-428c-8ae7-879c02c8c0b2.mp4
**Reminder** …

fix: invite dropdown allow select multiple

---

invenio_communities/communities/resolver.py

needed for https://github.com/inveniosoftware/invenio-app-rdm/pull/1626

community resolver: add community visibility to expanded object

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SelectedMembers.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/GroupTabPane.js

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1600
* needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1605
https://user-images.githubusercontent.com/15194802/169237992-f4a0504e-e2d1-4139-aa0b-cf2750b802a4.mp4

inivitation: fix "jumping" of modal

---

invenio_communities/communities/resources/config.py
invenio_communities/communities/resources/resource.py
invenio_communities/errors.py
tests/communities/test_resources.py

Fixes typo in passing argument (closes #667)
Adds `CommunityFeaturedEntryDoesNotExistError` to error_handler.
Adds `featured_id` to `request_view_args`, so it is accessible on routes.
Add test cases for featured community endpoints.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contri …

667 featured communities api is broken

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SelectedMembers.js
invenio_communities/assets/semantic-ui/translations/invenio_communities/messages/en/translations.json
invenio_communities/assets/semantic-ui/translations/invenio_communities/messages/es/translations.json
invenio_communities/assets/semantic-ui/translations/invenio_communities/translations.pot

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1600
https://user-images.githubusercontent.com/15194802/169487243-b17ed67d-11bb-4faa-be26-5ef507c58d3c.mp4

invitation: update modal height

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ErrorMessage.js
invenio_communities/members/services/service.py

- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1602

global: add field_name to ValidationError exceptions

---

invenio_communities/generators.py
invenio_communities/permissions.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1648
https://user-images.githubusercontent.com/15194802/169497695-e01c2231-35f0-432d-98a2-8ef083877c6d.mp4

permissions: Grant curator access to requet tab

---

invenio_communities/assets/semantic-ui/js/invenio_communities/requests/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js

needed by https://github.com/inveniosoftware/invenio-app-rdm/pull/1653

request: add type labels

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html

* closes https://github.com/inveniosoftware/invenio-communities/issues/686

frontpage:  rename featured communities section 

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SearchDropdowns.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js

fixes react errors appearing the in the logs, mostly caused by incorrect prop types being passed or props being passed that are not defined/used in a child component
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository …

logs: clear up errors appearing in the console

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SearchDropdowns.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SearchFilters.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SearchResultsBulkActions.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsResultsContainer.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/InvitationsMembersModal.js

fix mobile view.
add status icon.
add extra space for user full name.
closes: inveniosoftware/invenio-app-rdm#1595
depends on: https://github.com/inveniosoftware/invenio-app-rdm/pull/1640
depends on: https://github.com/inveniosoftware/invenio-requests/pull/238

Invitations: fix tablet view [DEPENDENCIES]

---

invenio_communities/communities/records/systemfields/access.py
tests/members/test_members_resource.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1651

systemfields: update access description

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SelectedMembers.js

* closes: inveniosoftware/invenio-app-rdm#1514

i18next: remove missused i18n call

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SearchResultsRowCheckbox.js

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1713

members: align checkbox

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1704
needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1710

communities logo: set height to avoid breaking the layout

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ActionDropdown.js

Closes https://github.com/inveniosoftware/invenio-communities/issues/716

members: error popup disappears after successful action

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/communities/resources/config.py
invenio_communities/communities/resources/serializer.py
invenio_communities/communities/resources/ui_schema.py
invenio_communities/communities/schema.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/views/communities.py
invenio_communities/views/decorators.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1518
* needs https://github.com/inveniosoftware/invenio-rdm-records/pull/979

[NEEDS #invenio-vocabularies/pull/199 #invenio-rdm-records/pull/979]recources: add ui serializer

---

invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html

party closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1742

homepage: align searchbar and button

---

invenio_communities/__init__.py

release: v2.8.5

---

invenio_communities/communities/resources/resource.py
invenio_communities/communities/services/service.py
invenio_communities/searchapp.py

closes https://github.com/inveniosoftware/invenio-communities/issues/720

requests search: add expanded fields

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MemberSearchBar.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/RenameCommunitySlugButton.js

- Removes superfluous white space.
- Adjust field to look like other fields.
Refs: inveniosoftware/invenio-app-rdm#1707

global: Fixes strings marked for translation.

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/new.js

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1768

new community: add responsive widths for grid columns

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js

Closes https://github.com/inveniosoftware/react-invenio-deposit/issues/531
Needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1766 <<--- Screenshots available
- Removed custom classes as everything is covered in the general overrides in invenio-app-rdm (see linked PR)

members: cleanup table classes

---

invenio_communities/assets/semantic-ui/js/invenio_communities/requests/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests_items/ComputerTabletRequestsItems.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests_items/MobileRequestsItems.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests_items/RightBottomLabel.js

Refactor request actions.
Add request actions to invenio-communites.
closes: #702
Desktop:
Tablet:
Mobile:

Requests: re-design requests list view

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

closes https://github.com/inveniosoftware/invenio-communities/issues/732

community: added community visibility labels to header.

---

invenio_communities/members/resources/config.py

This PR fix REST-API 500 Internal server error when provide invalid UUID for the following routes:
- **GET {{baseURL}}/api/communities/{{com-id}}/members**
- **GET {{baseURL}}/api/communities/{{com-id}}/members/public**
- **GET {{baseURL}}/api/communities/{{com-id}}/invitations**
- **POST {{baseURL}}/api/communities/{{com-id}}/members**
- **POST {{baseURL}}/api/communities/{{com-id}}/invitations**
- **PUT {{baseURL}}/api/communities/{{com-id}}/members**
- **PUT {{baseURL}}/api/communities/{{com-id}}/invitations**
- **DELETE {{baseURL}}/api/communities/{{com-id}}/members**
- 
fix for issue [735](https://github.com/inveniosoftware/invenio-communities/issues/735) …

communities: add missing err res for invalid uuid

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1616
- Adds onerror logic to function

header: add onerror inline js to script

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MembersWithRoleSelection.js

closes https://github.com/inveniosoftware/invenio-communities/issues/749

invitations: added helptext for users profile visibility.

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities_items/ComputerTabletCommunitiesItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities_items/MobileCommunitiesItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests_items/ComputerTabletRequestsItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests_items/MobileRequestsItem.js

* closes: #748
Computer
Tablet
Mobile

Communties search: refactor UI to match the dashboard

---

invenio_communities/communities/services/config.py
invenio_communities/communities/services/service.py
tests/communities/test_resources.py
tests/communities/test_services.py

Add missing config for links template and update result list for featured communities search.
**Reminder**
1. You license your contribution under the same terms as the current repository’s …

Links missing featured communities

---

invenio_communities/communities/schema.py

- closes  https://github.com/inveniosoftware/invenio-vocabularies/issues/205
- requires https://github.com/inveniosoftware/invenio-vocabularies/pull/207
Tests are passing in local except those also broken in master, see https://github.com/inveniosoftware/invenio-communities/issues/769

Vocabulary schemas

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js

Communities search: fix mobile pagination [DEPENDS ON https://github.com/inveniosoftware/invenio-search-ui/pull/150]

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/communities/resources/resource.py

now will set the restriction param based on the community visibility and it will force the community logo in the settings page to always update so that any changes are immediately shown to the user, no matter the browser cache.
Now also shows a message telling the user that it may take a few moments before the changes to the community logo can be seen everywhere (because of the browser caching it for a certain amount of time)
some context on this PR can be found here: https://codimd.web.cern.ch/DpHiJGHSRlGGyPg1KNTcmw#
closes https://github.com/inveniosoftware/invenio-communities/issues/718

community logo: set restriction and force fresh image

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SearchDropdowns.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SearchFilters.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1697
- Adds icons to filter & sort dropdowns
- Adds spacing to sort-label
**Filter & sort in table-view**
**Sort in list view**

search dropdowns: add icons and labels to dropdowns

---

invenio_communities/members/records/api.py
invenio_communities/members/records/models.py
tests/members/test_members_services.py

Fetches community permissions based on the group a user is in.
**Reminder**
2. You agree that you have …

fix: fetch community group permissions

---

.gitignore
invenio_communities/__init__.py
setup.cfg

release: v2.9.0.dev0

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CustomFieldSerializer.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/communities/records/api.py
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json
invenio_communities/communities/resources/ui_schema.py
invenio_communities/communities/schema.py
invenio_communities/communities/searchconfig.py
invenio_communities/communities/services/components.py
invenio_communities/communities/services/config.py
invenio_communities/communities/services/customizations.py
invenio_communities/communities/services/sort.py
invenio_communities/ext.py
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/profile.html
invenio_communities/views/communities.py

communities: add custom fields support

---

invenio_communities/__init__.py

release: v2.9.0.dev2

---

invenio_communities/__init__.py
invenio_communities/assets/semantic-ui/js/invenio_communities/community/new.js

V2.9.0.dev3

---

invenio_communities/cli.py
invenio_communities/config.py

- closes https://github.com/inveniosoftware/invenio-communities/issues/794

cli: add custom fields validation before creation

---

invenio_communities/__init__.py
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CustomFieldSerializer.js

custom: process __key in arrays

---

invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json

- closes #803 
`archivedinvitations` and `members` where already strict

mappings: make strict

---

invenio_communities/__init__.py

release: v2.9.0.dev7

---

invenio_communities/config.py
invenio_communities/permissions.py
invenio_communities/templates/invenio_communities/mycommunities.html
invenio_communities/views/ui.py

ui: community creation dynamic error messages

---

invenio_communities/__init__.py
invenio_communities/cli.py
invenio_communities/views/communities.py

cli: prefix index name

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js
invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js

* closes: [inveniosoftware/invenio-administration#56](https://github.com/inveniosoftware/invenio-administration/issues/43)

Facets: move facets to invenio-search-ui REQUIRES [invenio-search-ui#162]

---

invenio_communities/__init__.py
invenio_communities/communities/services/components.py
setup.cfg

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1037

service: add system_created field to OAI set

---

.github/workflows/tests.yml
invenio_communities/cli.py
invenio_communities/communities/dumpers/featured.py
invenio_communities/communities/records/api.py
invenio_communities/communities/records/mappings/os-v1/__init__.py
invenio_communities/communities/records/mappings/os-v1/communities/communities-v1.0.0.json
invenio_communities/communities/resources/resource.py
invenio_communities/communities/services/service.py
invenio_communities/fixtures/tasks.py
invenio_communities/generators.py
invenio_communities/members/records/api.py
invenio_communities/members/records/mappings/os-v1/__init__.py
invenio_communities/members/records/mappings/os-v1/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/os-v1/communitymembers/members/member-v1.0.0.json
invenio_communities/members/resources/resource.py
invenio_communities/members/services/config.py
invenio_communities/members/services/service.py
run-tests.sh
setup.cfg
tests/communities/test_cli.py
tests/communities/test_resources.py
tests/communities/test_services.py
tests/members/test_members_components.py

Requires https://github.com/inveniosoftware/invenio-search/pull/216

global: make search-engine-agnostic

---

invenio_communities/assets/semantic-ui/js/invenio_communities/requests/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests_items/ComputerTabletRequestsItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests_items/MobileRequestsItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests_items/RequestsResultProps.js

* move action buttons to a dropdown
* closes: inveniosoftware/invenio-requests#264

Community requests mobile: center content

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities-carousel/CarouselItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities-carousel/CommunitiesCarousel.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities-carousel/index.js
invenio_communities/templates/semantic-ui/invenio_communities/macros/communities_carousel.html
invenio_communities/webpack.py

Closes https://github.com/inveniosoftware/invenio-communities/issues/819
Needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1943
<video src="https://user-images.githubusercontent.com/21052053/196754148-ba3e7ee1-64bb-4ea6-99d3-4cd6eae334b0.mov" />

components: add communities carousel

---

invenio_communities/communities/services/service.py
invenio_communities/fixtures/tasks.py

- closes: https://github.com/zenodo/zenodo-rdm/issues/52

add logo uploading to demo community creation

---

invenio_communities/assets/semantic-ui/js/invenio_communities/requests/index.js

* closes: inveniosoftware/invenio-requests#264

RequestsActions: fix merging issues

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/featured-communities/FeaturedCommunities.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/featured-communities/FeaturedCommunity.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/featured-communities/index.js
invenio_communities/templates/semantic-ui/invenio_communities/macros/featured_communities.html
invenio_communities/webpack.py

* closes https://github.com/zenodo/who-rdm/issues/2

macro: display featured communities

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities_items/ComputerTabletCommunitiesItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities_items/MobileCommunitiesItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/featured-communities/FeaturedCommunities.js
invenio_communities/searchapp.py

closes: zenodo/zenodo-rdm#48
Communities computer tablet search:
Communities mobile search:
Communities dashboard computer tablet:
Communities dashboard mobile:

Communities search: add data to the search results

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

Closes https://github.com/inveniosoftware/invenio-theme/issues/301

header: add has-placeholder class

---

invenio_communities/fixtures/tasks.py

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1132

task: allow to feature a demo community

---

invenio_communities/communities/resolver.py
invenio_communities/communities/services/links.py
invenio_communities/communities/services/results.py
invenio_communities/members/services/schemas.py

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1987

expand: pass identity when picking fields

---

.gitignore
invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js

Closes https://github.com/inveniosoftware/invenio-communities/issues/847
- Adds the results counter and sort options to the community records-search

community details search: add search results counter and sort

---

CHANGES.rst
invenio_communities/__init__.py

release: v4.0.3

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

* closes: #849
Computer:
Tablet:
Mobile:

Community: align properly community details header

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMemberBulkActions.js

* the destructuring was causing actionParam evaluated as undefined

communities: fix destructuring statement

---

invenio_communities/communities/schema.py

Closes https://github.com/inveniosoftware/invenio-administration/issues/149
Adds title and description to community featured schema (start date).

community featured schema: add title and description

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/administration/communities.py
invenio_communities/config.py

administration: add disable menu entry on demand

---

invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html

Search button needs an accesible name. fixes #865
**Reminder**
1. You license your contribution under the same terms as the current repository’s …

[#865] Add Aria Label to Search Button

---

invenio_communities/communities/services/results.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
tests/conftest.py

Closes https://github.com/inveniosoftware/invenio-communities/issues/880

community header: align title and restricted label

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/os-v1/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/os-v2/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json
invenio_communities/communities/records/systemfields/access.py
invenio_communities/communities/resolver.py
invenio_communities/communities/resources/ui_schema.py
invenio_communities/communities/schema.py
invenio_communities/generators.py
invenio_communities/permissions.py
invenio_communities/views/communities.py

addresses https://github.com/inveniosoftware/invenio-communities/issues/871

implement direct publish

---

CHANGES.rst
invenio_communities/__init__.py

release: v5.0.0

---

CHANGES.rst
invenio_communities/__init__.py

release: v5.0.1

---

invenio_communities/communities/__init__.py
invenio_communities/communities/records/systemfields/access.py
invenio_communities/communities/resources/resource.py
invenio_communities/communities/services/__init__.py
invenio_communities/communities/services/components.py
invenio_communities/communities/services/config.py

- includes https://github.com/inveniosoftware/invenio-communities/pull/895 
- closes https://github.com/inveniosoftware/invenio-communities/issues/818

community access: make enum validation a class function

---

invenio_communities/communities/resources/config.py
invenio_communities/communities/services/config.py
invenio_communities/ext.py

- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2149

config: normalize names to plural (communities)

---

invenio_communities/communities/resources/config.py
invenio_communities/communities/resources/resource.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2076

resource: allow to exclude communities on search

---

invenio_communities/communities/resources/config.py
invenio_communities/communities/resources/resource.py

* This reverts commit https://github.com/jrcastro2/invenio-communities/commit/042c3e74e25737b858e68e1903b7091448cb2865.
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2076
* replaced by https://github.com/inveniosoftware/invenio-rdm-records/pull/1265

Revert "resource: allow to exclude communities on search"

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/SuccessIcon.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/index.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/index.js
invenio_communities/communities/services/service.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2076

successIcon: allow to pass content

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/DangerZone.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/DeleteCommunityModal.js

* improve error handling
* closes https://github.com/inveniosoftware/invenio-communities/issues/929
TODO:
- https://github.com/inveniosoftware/invenio-communities/issues/935
Previews:
Healthy flow:
Error  flow:

delete community: improve confirmation modal

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/searchComponents/CommunitiesResults.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SearchResultsBulkActions.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsResults.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/components/MembersResult.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/LogoUploader.js
invenio_communities/errors.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2162

translations: fix string concatenation and pluralizaton

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/new.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/LogoUploader.js
invenio_communities/webpack.py

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1276

assets: move deposit components to rdm-records

---

invenio_communities/members/services/config.py

closes https://github.com/inveniosoftware/invenio-records-resources/issues/447

search: added terms safelisting

---

invenio_communities/members/records/mappings/os-v1/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/os-v1/communitymembers/members/member-v1.0.0.json
invenio_communities/members/records/mappings/os-v2/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/os-v2/communitymembers/members/member-v1.0.0.json
invenio_communities/members/records/mappings/v7/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/v7/communitymembers/members/member-v1.0.0.json

* added appropriate mappings
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2069

preferences: add support for preferences.locale and preferences.timezone

---

invenio_communities/members/records/mappings/os-v1/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/os-v1/communitymembers/members/member-v1.0.0.json
invenio_communities/members/records/mappings/os-v2/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/os-v2/communitymembers/members/member-v1.0.0.json
invenio_communities/members/records/mappings/v7/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/v7/communitymembers/members/member-v1.0.0.json

ref https://github.com/inveniosoftware/invenio-notifications/issues/3
Add notification preferences to mapping files.
**Reminder**
1. You license your contribution under the same terms as the …

mappings: add notification preferences to mappings

---

invenio_communities/communities/services/config.py
invenio_communities/ext.py
invenio_communities/members/services/config.py
invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html
invenio_communities/views/communities.py
invenio_communities/views/ui.py

* Add check for permission to display create button
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/55
Hide "New community" button if not allowed to create them.

service: make permission policy configurable

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/LogoUploader.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/RenameCommunitySlugButton.js
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/curation_policy.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/pages.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/privileges.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/profile.html

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2208
- Adds aria-attributes for tabs
- Adds focusing on first interactive element when opening modal
- Adds focusing on modal trigger when closing modal
- Adds section to tab panel
- Adds correct heading level to sections
No visual changes, only functionality.

community settings: fix a11y for tabs and modals

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/new.js
invenio_communities/communities/services/components.py
invenio_communities/config.py
invenio_communities/generators.py
invenio_communities/permissions.py
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html
invenio_communities/templates/semantic-ui/invenio_communities/new.html
invenio_communities/views/communities.py
invenio_communities/views/ui.py
tests/communities/test_resources.py
tests/conftest.py

closes https://github.com/zenodo/zenodo-rdm/issues/250
Manages community access status.
If the user is an admin, the new config variable will have no effect on the user's UX.
If it is a normal user, they are not allowed to change the access rights on the backend and also not able to see the options on the frontend.
**Reminder** …

community access: manage access 

---

invenio_communities/assets/semantic-ui/js/invenio_communities/administration/FeatureModal.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesCarousel/CommunitiesCarousel.js
invenio_communities/templates/semantic-ui/invenio_communities/macros/communities_carousel.html

Closes https://github.com/inveniosoftware/invenio-communities/issues/964
- Adds placeholder for `<CommunitiesCarousel />` in both Jinja & React.
- Fixes a few console errors for `FeatureModal`
https://github.com/inveniosoftware/invenio-communities/assets/21052053/0606fbd9-a177-47a9-b1e6-7d19120fa6ad

CommunitiesCarousel: Add placeholder for loading

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesCarousel/CommunitiesCarousel.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesCarousel/index.js
invenio_communities/templates/semantic-ui/invenio_communities/macros/communities_carousel.html

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/54

assets: configure number of items in carousel

---

invenio_communities/communities/schema.py

* closes https://github.com/zenodo/zenodo-rdm/issues/284

schemas: inherit community ghost from base schema

---

tests/conftest.py

tests: fix users update

---

invenio_communities/cache/cache.py
invenio_communities/utils.py

* removes unnecessary function

cache: updates abstract cache class

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.0.1

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/index.js

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2180

members: export ErrorPopup

---

invenio_communities/views/ui.py

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2297

communities menu: change requests icon

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.1.0

---

invenio_communities/members/services/request.py

Closes https://github.com/inveniosoftware/invenio-requests/issues/328
Reorders actions to "accept", "decline", "cancel".

available_actions: reorder actions

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.1.1

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.1.2

---

CHANGES.rst
MANIFEST.in
invenio_communities/__init__.py
invenio_communities/members/services/service.py
invenio_communities/notifications/builders.py
invenio_communities/templates/semantic-ui/invenio_notifications/community-invitation.submit.jinja
invenio_communities/views/api.py
tests/conftest.py
tests/members/test_members_resource.py
tests/members/test_members_services.py

services: add notification op on invite
tests: add testcase for invitation notification
closes #889 
depends on https://github.com/inveniosoftware/invenio-requests/pull/321
Add a notification builder for member invitations and register NotificationOP on member invitation.
The template contains the community name, member role, a link to the request and the additional invitation message (if provided).
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/archit …

notifications: add invitation builder and template

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/searchComponents/CommunitiesSearchLayout.js
invenio_communities/templates/semantic-ui/invenio_communities/details/about/index.html
invenio_communities/templates/semantic-ui/invenio_communities/details/curation_policy/index.html
invenio_communities/templates/semantic-ui/invenio_communities/details/members/base.html
invenio_communities/templates/semantic-ui/invenio_communities/details/requests/index.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html
invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html
invenio_communities/templates/semantic-ui/invenio_communities/search.html
invenio_communities/utils.py
invenio_communities/views/communities.py

Requires https://github.com/inveniosoftware/invenio-oauthclient/pull/310

search: inject can_create permission

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.2.1

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.2.2

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.2.3

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.3.0

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemMobile.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/labels/CommunityTypeLabel.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/new.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/searchComponents/CommunitiesResults.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/searchComponents/CommunitiesSearchLayout.js
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/details/macros/access-status-label.html
invenio_communities/templates/semantic-ui/invenio_communities/search.html

Closes https://github.com/zenodo/zenodo-rdm/issues/410, closes https://github.com/zenodo/rdm-project/issues/209

Communities search: Update search page layout and items

---

invenio_communities/generators.py
invenio_communities/permissions.py

* close inveniosoftware/invenio-rdm-records#1226

permissions: extract base permissions

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.5.0

---

invenio_communities/requests/user_moderation/__init__.py
invenio_communities/requests/user_moderation/actions.py
setup.cfg

closes https://github.com/inveniosoftware/invenio-requests/issues/344

moderation: updated action names.

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.6.0

---

invenio_communities/communities/services/components.py
invenio_communities/config.py

* closes https://github.com/zenodo/rdm-project/issues/202

oai-pmh: take oai sets prefix from config

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.7.0

---

invenio_communities/communities/services/components.py
tests/communities/test_resources.py

* closes https://github.com/zenodo/zenodo-rdm/issues/470

components: fix visibility permission check

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/communities/services/service.py
tests/communities/test_alembic.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2384

service: exclude created requests from search result

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/new.js

Closes  [Issue#1007](https://github.com/inveniosoftware/invenio-communities/issues/1007)

Fix Issue #1007 -Added Ids to TextFields

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/searchComponents/CommunitiesSearchBarElement.js
invenio_communities/templates/semantic-ui/invenio_communities/frontpage.html

Closes https://github.com/inveniosoftware/invenio-search-ui/issues/180

search bar: add aria-label

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.7.3

---

CHANGES.rst
invenio_communities/__init__.py
setup.cfg

- installation: bump invenio-vocabularies
- release: v7.7.4

Bump invenio-vocabularies and release v7.7.4

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/DeleteCommunityModal.js

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2416
- Fixes missing label error for text field
- Styling fixes

delete community modal: fix styling

---

.github/workflows/pypi-publish.yml
.github/workflows/tests.yml
invenio_communities/alembic/5c68d45c80f0_add_deletion_status_to_communities.py
invenio_communities/communities/records/api.py
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/jsonschemas/communities/definitions-v2.0.0.json
invenio_communities/communities/records/mappings/os-v1/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/os-v2/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json
invenio_communities/communities/records/models.py
invenio_communities/communities/records/systemfields/deletion_status.py
invenio_communities/communities/records/systemfields/tombstone.py
invenio_communities/communities/schema.py
setup.cfg
tests/communities/test_tombstone.py

Basically copied over and adjusted from RDM-Records: https://github.com/inveniosoftware/invenio-rdm-records/pull/1386

Add data model for community deletion

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.8.0

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/ActionDropdown.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/MembersSearchBarElement.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/RemoveMemberModal.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/RadioSelection.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SearchResultsBulkActions.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/bulk_actions/SearchResultsRowCheckbox.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/dropdowns.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationsSearchBarElement.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/InvitationsMembersModal.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/curationPolicy/CurationPolicyForm.js

Closes Issue #1022 
**Reminder**
2. You agree that you have the right to license your contribution under …

Ay11 community view

---

invenio_communities/communities/services/sort.py

* partially closes https://github.com/zenodo/rdm-project/issues/177

service: fix sort param modifying sort options variable

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/DangerZone.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/profile.html
invenio_communities/views/communities.py

* closes https://github.com/zenodo/zenodo-rdm/issues/545

settings: Hide community rename based on permissions

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/pages/CommunityPagesForm.js

Closes https://github.com/zenodo/rdm-project/issues/261

settings: remove hidden divider from pages

---

invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html

Closes https://github.com/zenodo/rdm-project/issues/260

settings menu: rename curation policy menu item to review policy

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.13.0

---

invenio_communities/searchapp.py

searchapp: reduce the pagination options to 10 and 20

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemComputer.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemMobile.js
invenio_communities/communities/resources/config.py
invenio_communities/errors.py
invenio_communities/records/records/systemfields/communities/manager.py
tests/records/test_mockrecords_api.py

* closes https://github.com/zenodo/rdm-project/issues/188

default community: add possibility to set to None

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/views/communities.py

* closes https://github.com/zenodo/rdm-project/issues/262

header: add manage community button

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.15.0

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/DeleteCommunityModal.js
invenio_communities/communities/resources/ui_schema.py
invenio_communities/communities/services/service.py
invenio_communities/errors.py
invenio_communities/templates/semantic-ui/invenio_communities/tombstone.html

Fixed the following issue with delete community modal.
**Reminder**
2. You agree that you have the right …

community: fixed delete community modal

---

invenio_communities/views/ui.py

Closes Issue #1045 
**Reminder**
2. You agree that you have the right to license your contribution under …

community: added ui variables for tombstone

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/views/ui.py

* closes https://github.com/zenodo/rdm-project/issues/324

ui: allow slashes in communities urls

---

invenio_communities/communities/schema.py

Fixes https://github.com/zenodo/rdm-project/issues/423
Depends on: https://github.com/inveniosoftware/marshmallow-utils/pull/74
Update to new URL field to add support for `_` in subdomains.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …

communities: schema: CommunityMetadata: Use custom URL field

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.16.0

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/curationPolicy/CurationPolicyForm.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/pages/CommunityPagesForm.js

- settings-ui: adjust curation and page limit to 5k
- release: v7.16.1

Fix max lengths in UI settings form and release v7.16.1

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/views/ui.py

* closes https://github.com/zenodo/rdm-project/issues/433
In collaboration with @fenekku . Thank you for your contribution ❤️

community logo: fix rendering a placeholder

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.16.2

---

CHANGES.rst
invenio_communities/__init__.py

release: v7.16.3

---

invenio_communities/communities/schema.py

* closes https://github.com/zenodo/rdm-project/issues/327

schema: avoid loading None value in custom_fields

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/views/ui.py

Backport of https://github.com/inveniosoftware/invenio-communities/commit/558aafadff099d91b258b73e476bff3a9e3abba2
**Reminder**
2. You agree that …

Backport community logo filter to 4.x (InvenioRDM STS v11)

---

invenio_communities/__init__.py
invenio_communities/views/ui.py

Hotfix to fix backported UI imports. My bad, so I fix! Will merge and release to mitigate any pickup.
**Reminder** …

Fix imports

---

invenio_communities/views/ui.py

closes https://github.com/zenodo/rdm-project/issues/486

views: header menu entry visible for unauth users.

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/index.js

Adds overridable tags and overridable context  to the community profile form so elements can easily be changed or hidden. 
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.

Add overridable tags and  overridable context to community profile form.

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/pages/CommunityPagesForm.js
invenio_communities/communities/schema.py
invenio_communities/fixtures/demo.py
tests/communities/test_resources.py

Closes https://github.com/zenodo/rdm-project/issues/520

pages: update character limit to 50k

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/GroupTabPane.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/MembersWithRoleSelection.js
invenio_communities/templates/semantic-ui/invenio_communities/details/curation_policy/index.html
invenio_communities/webpack.py

Partially Closes Issue https://github.com/zenodo/rdm-project/issues/421
**Reminder**
2. You agree that …

editor: replaced ckeditor with tinymce

---

.github/workflows/tests.yml
CHANGES.rst
invenio_communities/__init__.py
invenio_communities/communities/services/service.py
invenio_communities/generators.py
invenio_communities/members/services/service.py
setup.cfg
tests/conftest.py

Bumped dependencies and release v9.0.0

---

invenio_communities/alembic/72b37bb4119c_create_indeces_for_bucket_id.py
invenio_communities/communities/records/models.py

* adds alembic recipe
* closes https://github.com/zenodo/rdm-project/issues/640
**NEEDS**  https://github.com/inveniosoftware/invenio-records-resources/pull/554

models: add index on bucket_id

---

invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/systemfields/parent_community.py
invenio_communities/communities/schema.py
invenio_communities/communities/services/results.py
invenio_communities/utils.py
tests/communities/test_parent_community.py
tests/communities/test_services.py

* closes https://github.com/zenodo/zenodo-rdm/issues/696

Add dereferencing parent comm

---

invenio_communities/records/records/systemfields/communities/field.py
invenio_communities/records/records/systemfields/communities/manager.py

- Closes https://github.com/zenodo/zenodo-rdm/issues/698
**Reminder**
1. You license your contribution under the same terms as the current repository’s …

Record community indexing

---

invenio_communities/templates/semantic-ui/invenio_communities/community_theme_template.css

Closes Issue [#719](https://github.com/zenodo/zenodo-rdm/issues/719)
- frontpage: label colouring should follow the EC theme
**Reminder**
1. You license your contribution under the same terms as …

ui: added class for label and text color

---

invenio_communities/communities/schema.py
invenio_communities/communities/services/components.py
invenio_communities/communities/services/service.py
invenio_communities/permissions.py
tests/communities/test_services.py

Merge after: #1086
Added service method to add parent to a community.

service: add update_parent_community service method

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesCarousel/index.js

Remove console.log from communitiesCarousel index.js for cleaner code
**Reminder**
2. You agree that you …

Remove console.log from communitiesCarousel

---

invenio_communities/views/ui.py

Closes Issue https://github.com/zenodo/zenodo-rdm/issues/743
**Reminder** …

submenu: reordered the submenu for community

---

invenio_communities/templates/semantic-ui/invenio_communities/community_theme_template.css

Closes Issue https://github.com/zenodo/zenodo-rdm/issues/747
**Reminder** …

theme: updated css

---

invenio_communities/communities/services/service.py
tests/communities/test_services.py

closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1677

services: added bulk 'add to parent' call

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges/CommunityPriviledgesForm.js
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/os-v1/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/os-v2/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json
invenio_communities/communities/records/systemfields/access.py
invenio_communities/communities/schema.py
invenio_communities/communities/services/config.py
invenio_communities/members/services/service.py
invenio_communities/permissions.py
invenio_communities/views/communities.py
invenio_communities/views/ui.py
tests/communities/test_resources.py
tests/conftest.py
tests/members/test_members_resource.py
tests/members/test_members_services.py

- Closes https://github.com/inveniosoftware/invenio-communities/issues/1108

global: implement access.members_visibility field

---

CHANGES.rst
invenio_communities/__init__.py

release: v12.1.1

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities_items/ComputerTabletCommunitiesItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communities_items/MobileCommunitiesItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/frontpage.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/search.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/InvitationResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/components/MembersResultsGridItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/manager_view/ManagerMembersResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/members/public_view/PublicMembersResultItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/requests/requests.js

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2693

Fix html rendering

---

CHANGES.rst
invenio_communities/__init__.py

- Release v4.2.2
- Added missing entry in `CHANGES` for release v4.2.1

release: v4.2.2

---

invenio_communities/communities/records/systemfields/is_verified.py
invenio_communities/communities/services/components.py
invenio_communities/communities/services/facets.py
invenio_communities/communities/services/links.py
invenio_communities/communities/services/results.py
invenio_communities/communities/services/sort.py
invenio_communities/communities/services/uow.py
invenio_communities/ext.py
invenio_communities/requests/user_moderation/__init__.py
invenio_communities/requests/user_moderation/actions.py
invenio_communities/searchapp.py
invenio_communities/subcommunities/__init__.py
invenio_communities/subcommunities/resources/__init__.py
invenio_communities/subcommunities/resources/config.py
invenio_communities/subcommunities/resources/resource.py
invenio_communities/subcommunities/services/__init__.py
invenio_communities/subcommunities/services/config.py
invenio_communities/subcommunities/services/request.py
invenio_communities/subcommunities/services/schema.py
invenio_communities/subcommunities/services/service.py
invenio_communities/tasks.py
invenio_communities/views/__init__.py
invenio_communities/views/api.py
setup.cfg
tests/communities/test_subcommunities.py
tests/conftest.py

closes https://github.com/inveniosoftware/invenio-communities/issues/1147

subcommunities: added base request and service.

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/new.js
invenio_communities/communities/schema.py
tests/communities/test_resources.py

1. Cast slug to lowercase to communicate to users what the URL will actually look like
2. Improve the error message
Before and after (changes highlighted with arrows):
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository …

UX: improve new community page

---

invenio_communities/assets/semantic-ui/js/invenio_communities/api/CommunityApi.js
invenio_communities/assets/semantic-ui/js/invenio_communities/subcommunity/new.js
invenio_communities/config.py
invenio_communities/templates/semantic-ui/invenio_communities/details/new_subcommunity.html
invenio_communities/views/communities.py
invenio_communities/views/ui.py
invenio_communities/webpack.py

Close #1150 
**Frontend**
**Reminder**
2. You agree that you have the right …

UI: add 'new subcommunity' form

---

invenio_communities/assets/semantic-ui/js/invenio_communities/subcommunity/new.js

close https://github.com/zenodo/zenodo-rdm/issues/884

bug: allow adding existing communities

---

invenio_communities/assets/semantic-ui/js/invenio_communities/subcommunity/new.js

close https://github.com/zenodo/zenodo-rdm/issues/885

bug: filter out communities that have a parent or can have children

---

invenio_communities/assets/semantic-ui/js/invenio_communities/subcommunity/new.js

sort: explicitly sort by newest first

---

invenio_communities/assets/semantic-ui/js/invenio_communities/subcommunity/new.js

closes https://github.com/zenodo/zenodo-rdm/issues/882

Subcommunities: fix request redirect url after new request (UI)

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2602

profile: rename award label

---

invenio_communities/subcommunities/resources/config.py
invenio_communities/subcommunities/services/errors.py
invenio_communities/subcommunities/services/service.py

closes https://github.com/zenodo/zenodo-rdm/issues/902

subcommunities: check for parent children allow

---

invenio_communities/assets/semantic-ui/js/invenio_communities/subcommunity/new.js
invenio_communities/templates/semantic-ui/invenio_communities/details/new_subcommunity.html

closes https://github.com/zenodo/zenodo-rdm/issues/904

subcommunities: fix request redirect url

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/subcommunities/services/service.py

- **subcommunities: pass "payload" to request creation**
- **📦 release: v14.5.0**
**Frontend**
**Reminder**
1. You license your contribution under the same terms as …

Fix subcommunities reuqest payload passing and release v14.5.0

---

invenio_communities/communities/records/systemfields/is_verified.py

- fix(verified): group not handled
- [commit](https://github.com/inveniosoftware/invenio-communities/pull/1174/commits/c17a20455bbbbf821ba5677c0ff198fc7f0c3327) fixes https://github.com/inveniosoftware/invenio-app-rdm/issues/2639

fix is verified

---

.github/workflows/tests.yml
invenio_communities/communities/records/systemfields/is_verified.py
invenio_communities/communities/services/service.py

- fix(verified): the owner is not exclusively a user
- fix(logo): not fully deleted

backport to v13

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js

- profile: rename award label
- release: v13.0.5

maint v13 0 4 cherry picked

---

invenio_communities/requests/user_moderation/actions.py
invenio_communities/requests/user_moderation/tasks.py
setup.cfg

- Closes https://github.com/zenodo/zenodo-rdm/issues/939

user_moderation: dispatch Celery tasks for each community operation

---

invenio_communities/assets/semantic-ui/js/invenio_communities/settings/pages/index.js
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/systemfields/access.py
invenio_communities/communities/schema.py
invenio_communities/generators.py
invenio_communities/permissions.py
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/pages.html
invenio_communities/views/communities.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/176

review policy: allow all community members to submit records to community without review

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/InvitationsMembersModal.js

This is a backport of https://github.com/inveniosoftware/invenio-communities/pull/1185 to v13.x

Backport: Community member invitation modal fix

---

invenio_communities/assets/semantic-ui/js/invenio_communities/api/UsersApi.js
invenio_communities/assets/semantic-ui/js/invenio_communities/members/invitations/invitationsModal/InvitationsMembersModal.js

Fixes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2752

InvitationsModal: Use suggest API for finding users

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesCarousel/CarouselItem.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesCarousel/CommunitiesCarousel.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges/CommunityPrivilegesForm.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/CommunityProfileForm.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/submissionPolicy/SubmissionPolicyForm.js
invenio_communities/assets/semantic-ui/js/invenio_communities/settings/submissionPolicy/index.js
invenio_communities/communities/records/jsonschemas/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/os-v1/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/os-v2/communities/communities-v1.0.0.json
invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json
invenio_communities/communities/records/systemfields/access.py
invenio_communities/communities/resources/ui_schema.py
invenio_communities/communities/schema.py
invenio_communities/config.py
invenio_communities/fixtures/demo.py
invenio_communities/generators.py
invenio_communities/permissions.py
invenio_communities/subcommunities/services/schema.py
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/base.html
invenio_communities/templates/semantic-ui/invenio_communities/details/settings/submission_policy.html
invenio_communities/views/communities.py
invenio_communities/views/ui.py
invenio_communities/webpack.py
tests/communities/test_community_ui_serializer.py
tests/communities/test_resources.py
tests/conftest.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/158
Communities carousel:
Grayed out button:
New setting:

community settings: handle record submission policy setting

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

ROR recommends linking the name as well https://ror.readme.io/docs/display#inline-ror-id
Before:
After:
**Frontend**
**Reminder**
1. You license your contribution …

UX: link org name to ROR

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

Before:
After:
**Frontend**
**Reminder** …

bug: fix display of non-ROR orgs and fix commas

---

invenio_communities/assets/semantic-ui/js/invenio_communities/members/components/MembersSearchBarElement.js

closes https://github.com/inveniosoftware/invenio-communities/issues/1136
[Screencast from 09-16-2024 03:56:31 PM.webm](https://github.com/user-attachments/assets/48149992-c029-4dc7-b2e5-b6059f73a10a)

members-search: fix negative paging

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/communities/records/api.py
invenio_communities/communities/records/mappings/os-v1/communities/communities-v2.0.0.json
invenio_communities/communities/records/mappings/os-v2/communities/communities-v2.0.0.json
invenio_communities/communities/records/mappings/v7/communities/communities-v1.0.0.json

Partially closes inveniosoftware/invenio-vocabularies#403
Updates the mappings with subjects and orgs in the award
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the current …

mappings: updated awards with subj an orgs & 📦 release: v17.0.0

---

invenio_communities/communities/resources/config.py
invenio_communities/communities/resources/resource.py
invenio_communities/communities/services/config.py
invenio_communities/communities/services/service.py
invenio_communities/subcommunities/resources/config.py
invenio_communities/subcommunities/resources/resource.py
invenio_communities/subcommunities/services/service.py

closes https://github.com/zenodo/zenodo-rdm/issues/1013

subcommunities: moved endpoint to communities resource

---

invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

**Before**
**After**
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under …

ui: added verified icon and parent community

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemComputer.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityCompactItemMobile.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemMobile.js
invenio_communities/templates/semantic-ui/invenio_communities/details/header.html

Partially fixes inveniosoftware/invenio-communities#1234
Second iteration on changes in inveniosoftware/invenio-communities#1237
* Not relying on the verified field which is not serialized for non admins
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …

ui: verified icon display logic change

---

invenio_communities/assets/semantic-ui/js/invenio_communities/community/header/index.js

The original code flow is creating exceptions in case both DOM elements are not defined.
**Frontend**
**Reminder**
2. You …

ui: avoid exceptions if organizations list and request membership are not defined

---

invenio_communities/subcommunities/services/service.py

fix: extend invitation request expiry

---

invenio_communities/subcommunities/services/service.py

service: allow passing custom expires_at

---

.github/workflows/pypi-publish.yml
.github/workflows/tests.yml
CHANGES.rst
docs/conf.py
invenio_communities/__init__.py
setup.cfg

- setup: bump major dependencies
- setup: change to reusable workflows
- release: v18.0.0.dev1

bump major

---

setup.cfg
tests/__init__.py
tests/cache/__init__.py
tests/communities/__init__.py
tests/members/__init__.py
tests/records/__init__.py
tests/records/conftest.py
tests/records/test_mockrecords_api.py

An __init__.py file is necessary for pytest v8.x to be able to detect all unique tests. Otherwise CI fails.
**Frontend**
**Reminder**
2. You agree …

tests: add __init__.py in all directories

---

invenio_communities/templates/semantic-ui/invenio_communities/administration/community_search.html

Side menu toggle and user profile dropdown did not trigger any events. Add missing JS on administration view for community_search.html.
closes https://github.com/inveniosoftware/invenio-communities/issues/910
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-un …

Frozen Admin Navbar

---

CHANGES.rst
invenio_communities/__init__.py
invenio_communities/communities/services/config.py
invenio_communities/errors.py
invenio_communities/templates/semantic-ui/invenio_communities/administration/community_search.html
invenio_communities/utils.py
tests/communities/test_resources.py
tests/conftest.py

- **tests: remove invenio-admin dependence**
- **bug: humanize byte size error on community image upload**
- **Include missing JS on admin community_search.html closes #910**
- **:package: release: v13.0.10**

backport + release 13.0.10

---

babel.ini

**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …

i18n: include jinja file encoding in babel.ini

---

invenio_communities/communities/services/facets.py
invenio_communities/members/services/facets.py

* the problem was that with gettext the translations for facets
have been only calculated on boot time.
* using lazy_gettext instead fixes that, because it calculates
the translation at the request level
Co-authored-by: Mirek Simek <miroslav.simek@cesnet.cz>
**Frontend**
**Reminder** …

I18n-backport-lazygettext

---

invenio_communities/notifications/generators.py
invenio_communities/permissions.py

- exclude system_user from notifs recipients
- add missing system_process service permissions
- closes CERNDocumentServer/cds-rdm#3527

notifs: exclude system_user

---

invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/RestoreConfirmation.js
invenio_communities/assets/semantic-ui/js/invenio_communities/administration/components/TombstoneForm.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemComputer.js
invenio_communities/assets/semantic-ui/js/invenio_communities/community/communitiesItems/CommunityItemMobile.js
invenio_communities/communities/schema.py
invenio_communities/communities/services/components.py
invenio_communities/communities/services/service.py
invenio_communities/members/resources/config.py
invenio_communities/members/services/components.py
invenio_communities/members/services/fields.py
invenio_communities/members/services/service.py
invenio_communities/roles.py
invenio_communities/views/communities.py

**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …

I18n-translations-backport

---

CHANGES.rst
invenio_communities/__init__.py

Please make sure to merge the following first: 
- https://github.com/inveniosoftware/invenio-communities/pull/1283
- https://github.com/inveniosoftware/invenio-communities/pull/1284
- https://github.com/inveniosoftware/invenio-communities/pull/1285
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-r …

Release-v13.0.11

---

invenio_communities/assets/semantic-ui/translations/invenio_communities/package-lock.json

**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …

translations: update package-lock.json

---

.github/workflows/tests.yml

* Change branch type from string to array
* Switch To [Centralised Workflows ](https://github.com/inveniosoftware/workflows)
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the …

CI: Switch To Centralised Workflows

---

invenio_communities/permissions.py
tests/communities/test_permissions.py

* the Disabled permission does not allow admins to perform operations

permissions: replace Disabled with SystemProcess

---

.readthedocs.yaml
MANIFEST.in
README.rst

Invenio communities has been in production for a long time, so it's no longer experimental. I also added some new readthedocs configs to try to get the docs to render again.
**Reminder**
1. You license your contribution under the same …

Update readme and docs
